In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt

# Cell line data:

In [2]:
data = pd.read_csv("data/1-9DDA.csv")
data

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9
0,Biognosys|iRT-Kit_WR_fusion,Biognosys|iRT-Kit_WR_fusion,1.759900e+09,2.190600e+09,2.700000e+09,2.919500e+09,2.929400e+09,2.746800e+09,2.749800e+09,2.739200e+09
1,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp|O76015|KR...,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp|O76015|KR...,0.000000e+00,0.000000e+00,0.000000e+00,1.035500e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,CON__A2I7N1;CON__A2I7N0,CON__A2I7N1;CON__A2I7N0,9.384300e+06,7.737700e+06,8.645900e+06,1.363800e+07,7.774400e+06,1.313200e+07,3.876500e+06,3.803800e+06
3,CON__A2I7N3,CON__A2I7N3,1.321800e+06,3.147300e+06,1.298300e+06,6.730600e+06,2.073200e+06,3.600100e+06,1.614700e+06,5.319600e+06
4,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...
5731,sp|Q9Y6Y0|NS1BP_HUMAN,sp|Q9Y6Y0|NS1BP_HUMAN,5.639500e+05,7.146100e+05,0.000000e+00,8.943900e+05,6.426200e+05,0.000000e+00,0.000000e+00,0.000000e+00
5732,sp|Q9Y6Y8|S23IP_HUMAN,sp|Q9Y6Y8|S23IP_HUMAN,5.718900e+06,5.683100e+06,7.192000e+06,4.491700e+06,4.680500e+06,5.076900e+06,3.266500e+06,7.789400e+06
5733,tr|B3KNS4|B3KNS4_HUMAN,tr|B3KNS4|B3KNS4_HUMAN,3.499400e+07,4.555700e+07,3.257200e+07,3.982800e+07,3.325000e+07,2.231400e+07,3.396600e+07,3.249400e+07
5734,tr|Q5TEC6|Q5TEC6_HUMAN,tr|Q5TEC6|Q5TEC6_HUMAN,3.716700e+09,2.771600e+09,2.120100e+09,2.258400e+09,1.576100e+09,2.463900e+09,1.716500e+09,2.386800e+09
5735,tr|Q9HB66|Q9HB66_HUMAN,tr|Q9HB66|Q9HB66_HUMAN,2.648000e+07,0.000000e+00,1.675700e+07,0.000000e+00,1.860600e+07,1.600200e+07,2.055600e+07,2.148100e+07

In [5]:
data["Protein IDs"].str.split("|")

0                          [Biognosys, iRT-Kit_WR_fusion]
1       [CON__A2A5Y0;CON__REFSEQ:XP_986630;sp, O76015,...
2                               [CON__A2I7N1;CON__A2I7N0]
3                                           [CON__A2I7N3]
4       [CON__ENSEMBL:ENSBTAP00000001528;sp, Q15811, I...
                              ...
5731                            [sp, Q9Y6Y0, NS1BP_HUMAN]
5732                            [sp, Q9Y6Y8, S23IP_HUMAN]
5733                           [tr, B3KNS4, B3KNS4_HUMAN]
5734                           [tr, Q5TEC6, Q5TEC6_HUMAN]
5735                           [tr, Q9HB66, Q9HB66_HUMAN]
Name: Protein IDs, Length: 5736, dtype: object

In [10]:
for col in ["g-1 ", "g-3", "g-4", "g-5", "g-6", "g-7", "g-8", "g-9"]:
    print(data[col].isnull().sum())

61
61
61
61
61
61
61
61

In [11]:
data[["Protein IDs","Majority protein IDs"]]

,Protein IDs,Majority protein IDs
0,Biognosys|iRT-Kit_WR_fusion,Biognosys|iRT-Kit_WR_fusion
1,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp|O76015|KR...,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp|O76015|KR...
2,CON__A2I7N1;CON__A2I7N0,CON__A2I7N1;CON__A2I7N0
3,CON__A2I7N3,CON__A2I7N3
4,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...
...,...,...
5731,sp|Q9Y6Y0|NS1BP_HUMAN,sp|Q9Y6Y0|NS1BP_HUMAN
5732,sp|Q9Y6Y8|S23IP_HUMAN,sp|Q9Y6Y8|S23IP_HUMAN
5733,tr|B3KNS4|B3KNS4_HUMAN,tr|B3KNS4|B3KNS4_HUMAN
5734,tr|Q5TEC6|Q5TEC6_HUMAN,tr|Q5TEC6|Q5TEC6_HUMAN
5735,tr|Q9HB66|Q9HB66_HUMAN,tr|Q9HB66|Q9HB66_HUMAN

In [16]:
data[(data["Protein IDs"] != data["Majority protein IDs"])]

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9
5,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030;sp...,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030,1.004200e+05,1.479200e+06,2.356400e+06,4.336100e+06,2.217300e+06,1.520600e+06,2.178100e+06,9.723400e+05
9,CON__ENSEMBL:ENSBTAP00000024146;sp|P01023|A2MG...,CON__ENSEMBL:ENSBTAP00000024146,1.718700e+07,5.008500e+07,3.625700e+07,8.075600e+07,3.682300e+07,3.509700e+07,4.019000e+07,2.903700e+07
21,CON__P00761;sp|Q9BYE2|TMPSD_HUMAN,CON__P00761,3.120800e+09,3.796000e+09,3.380200e+09,8.268500e+09,2.987200e+09,3.362400e+09,2.608200e+09,2.872000e+09
22,CON__P00978;sp|P02760|AMBP_HUMAN,CON__P00978,0.000000e+00,2.414200e+06,2.400900e+06,7.311400e+06,1.288600e+06,7.918900e+05,1.023600e+06,0.000000e+00
23,CON__P01044-1;CON__P01045-1;sp|P01042|KNG1_HUMAN,CON__P01044-1;CON__P01045-1,5.290200e+06,1.881300e+06,1.455300e+06,3.396100e+07,1.779300e+06,1.914300e+06,2.636000e+06,1.477700e+06
...,...,...,...,...,...,...,...,...,...,...
5669,sp|Q9Y5V3|MAGD1_HUMAN;sp|Q96JG8|MAGD4_HUMAN,sp|Q9Y5V3|MAGD1_HUMAN,5.295300e+06,3.264100e+06,3.828500e+06,3.972200e+06,3.138500e+06,4.572800e+06,2.650500e+06,2.522700e+06
5687,sp|Q9Y666|S12A7_HUMAN;sp|Q9UP95|S12A4_HUMAN;sp...,sp|Q9Y666|S12A7_HUMAN,8.784200e+06,1.486700e+07,1.018200e+07,1.549700e+07,1.345200e+07,9.505900e+06,9.837100e+06,8.170700e+06
5701,sp|Q9Y6D6|BIG1_HUMAN;sp|Q9UIA0|CYH4_HUMAN,sp|Q9Y6D6|BIG1_HUMAN,3.713900e+06,2.066700e+06,1.533500e+06,1.668800e+06,1.974600e+06,1.717300e+06,1.964100e+06,1.280900e+06
5709,sp|Q9Y6I3|EPN1_HUMAN;sp|Q9H201|EPN3_HUMAN,sp|Q9Y6I3|EPN1_HUMAN,8.152800e+06,7.269000e+06,1.026500e+07,8.743000e+06,7.980800e+06,3.364300e+06,1.517700e+07,7.554900e+06
5718,sp|Q9Y6M7|S4A7_HUMAN;sp|Q6U841|S4A10_HUMAN,sp|Q9Y6M7|S4A7_HUMAN,1.574200e+06,1.581900e+06,1.117400e+06,9.066200e+05,1.108200e+06,1.142800e+06,1.785400e+06,1.694300e+06

In [3]:
aux = data["Majority protein IDs"].str.split("|", expand=True)
aux

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,Biognosys,iRT-Kit_WR_fusion,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp,O76015,KRT38_HUMAN;CON__O76015;sp,O76014,KRT37_HUMAN;CON__O76014,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,CON__A2I7N1;CON__A2I7N0,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,CON__A2I7N3,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,CON__ENSEMBL:ENSBTAP00000001528;sp,Q15811,ITSN1_HUMAN,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5731,sp,Q9Y6Y0,NS1BP_HUMAN,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5732,sp,Q9Y6Y8,S23IP_HUMAN,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5733,tr,B3KNS4,B3KNS4_HUMAN,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5734,tr,Q5TEC6,Q5TEC6_HUMAN,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5735,tr,Q9HB66,Q9HB66_HUMAN,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [4]:
aux2 = aux[aux[3].isna()][[0,1,2]]
aux2

,0,1,2
0,Biognosys,iRT-Kit_WR_fusion,None
2,CON__A2I7N1;CON__A2I7N0,None,None
3,CON__A2I7N3,None,None
4,CON__ENSEMBL:ENSBTAP00000001528;sp,Q15811,ITSN1_HUMAN
5,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030,None,None
...,...,...,...
5731,sp,Q9Y6Y0,NS1BP_HUMAN
5732,sp,Q9Y6Y8,S23IP_HUMAN
5733,tr,B3KNS4,B3KNS4_HUMAN
5734,tr,Q5TEC6,Q5TEC6_HUMAN
5735,tr,Q9HB66,Q9HB66_HUMAN

In [35]:
for item in aux2[~aux2[1].isna()][1]:
    if ("Q" not in item)and("P" not in item)and("O" not in item):
        print(item)

iRT-Kit_WR_fusion
A0A1B0GUA6
A0A024RBG1
A0A0U1RRE5
A0A0U1RRL7
A0AV96
A0AVT1
A0FGR8
A0JNW5
A0MZ66
A1A4G5
A1A4S6
A1KXE4
A1L0T0
A1X283
A2A3N6
A3KMH1
A3KN83
A4D1E9
A4D263
A5D8V6
A5YKK6
A6ND36
A6NDG6
A6NHL2
A6NHR9
A6NJ78
A7KAX9
A8MTT3
A8MXV4
C9JLW8
L0R819
B3KNS4

In [36]:
aux2[~aux2[1].isna()]

,0,1,2
0,Biognosys,iRT-Kit_WR_fusion,None
4,CON__ENSEMBL:ENSBTAP00000001528;sp,Q15811,ITSN1_HUMAN
26,sp,P02533,K1C14_HUMAN;CON__P02533
36,sp,P05787,K2C8_HUMAN;CON__P05787
39,CON__P08727;sp,P08727,K1C19_HUMAN
...,...,...,...
5731,sp,Q9Y6Y0,NS1BP_HUMAN
5732,sp,Q9Y6Y8,S23IP_HUMAN
5733,tr,B3KNS4,B3KNS4_HUMAN
5734,tr,Q5TEC6,Q5TEC6_HUMAN
5735,tr,Q9HB66,Q9HB66_HUMAN

In [5]:
rem = list(set(aux.index)-set(aux2[~aux2[1].isna()].index))
len(rem)

225

In [6]:
rem_df = aux.iloc[rem]
rem_df

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
1,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp,O76015,KRT38_HUMAN;CON__O76015;sp,O76014,KRT37_HUMAN;CON__O76014,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,CON__A2I7N1;CON__A2I7N0,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,CON__A2I7N3,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,CON__ENSEMBL:ENSBTAP00000014147,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028,sp,P58317,ZN121_HUMAN;sp,Q6ZMS4,ZN852_HUMAN;sp,P0CG24,ZN883_HUMAN;sp,P17036,ZNF3_HUMAN;sp,P17023,...,Q5TYW1,ZN658_HUMAN,None,None,None,None,None,None,None,None
1007,sp,P07355,ANXA2_HUMAN;sp,A6NMY6,AXA2L_HUMAN,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3153,sp,Q6NZ67,MZT2B_HUMAN;sp,Q6P582,MZT2A_HUMAN,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3067,sp,Q5VST6,AB17B_HUMAN;sp,Q96GS6,AB17A_HUMAN,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3070,sp,Q969Z3,MARC2_HUMAN;sp,Q5VT66,MARC1_HUMAN,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [51]:
rem_df[rem_df[1].isna()][0].str.split(";", expand=True)

                                  0            1
2                       CON__A2I7N1  CON__A2I7N0
3                       CON__A2I7N3         None
5   CON__ENSEMBL:ENSBTAP00000007350  CON__P01030
6   CON__ENSEMBL:ENSBTAP00000014147         None
7   CON__ENSEMBL:ENSBTAP00000016046         None
..                              ...          ...
91                      CON__Q6IFX2         None
94                      CON__Q95121         None
97                      CON__Q9TRI1         None
98                      CON__Q9TTE1         None
99         CON__REFSEQ:XP_001252647         None

[78 rows x 2 columns]

In [52]:
rem_df[rem_df[4].isna()]

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
2,CON__A2I7N1;CON__A2I7N0,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,CON__A2I7N3,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,CON__ENSEMBL:ENSBTAP00000014147,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,CON__ENSEMBL:ENSBTAP00000016046,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,CON__Q6IFX2,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
94,CON__Q95121,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
97,CON__Q9TRI1,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
98,CON__Q9TTE1,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
99,CON__REFSEQ:XP_001252647,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

Those with multiple majority proteins should be excluded.

Keep: those with NA in column 4 --> then work further with these only.

In [7]:
aux = data["Majority protein IDs"].str.split("|", expand=True)
aux["original"] = data["Majority protein IDs"]
aux = aux[["original"]+[i for i in range(0,41)]]
aux

,original,0,1,2,3,4,5,6,7,8,...,31,32,33,34,35,36,37,38,39,40
0,Biognosys|iRT-Kit_WR_fusion,Biognosys,iRT-Kit_WR_fusion,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp|O76015|KR...,CON__A2A5Y0;CON__REFSEQ:XP_986630;sp,O76015,KRT38_HUMAN;CON__O76015;sp,O76014,KRT37_HUMAN;CON__O76014,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,CON__A2I7N1;CON__A2I7N0,CON__A2I7N1;CON__A2I7N0,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,CON__A2I7N3,CON__A2I7N3,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,CON__ENSEMBL:ENSBTAP00000001528;sp,Q15811,ITSN1_HUMAN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5731,sp|Q9Y6Y0|NS1BP_HUMAN,sp,Q9Y6Y0,NS1BP_HUMAN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5732,sp|Q9Y6Y8|S23IP_HUMAN,sp,Q9Y6Y8,S23IP_HUMAN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5733,tr|B3KNS4|B3KNS4_HUMAN,tr,B3KNS4,B3KNS4_HUMAN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5734,tr|Q5TEC6|Q5TEC6_HUMAN,tr,Q5TEC6,Q5TEC6_HUMAN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5735,tr|Q9HB66|Q9HB66_HUMAN,tr,Q9HB66,Q9HB66_HUMAN,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [23]:
aux[aux[4].isna()].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5589 entries, 0 to 5735
Data columns (total 42 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   original  5589 non-null   object
 1   0         5589 non-null   object
 2   1         5511 non-null   object
 3   2         5510 non-null   object
 4   3         0 non-null      object
 5   4         0 non-null      object
 6   5         0 non-null      object
 7   6         0 non-null      object
 8   7         0 non-null      object
 9   8         0 non-null      object
 10  9         0 non-null      object
 11  10        0 non-null      object
 12  11        0 non-null      object
 13  12        0 non-null      object
 14  13        0 non-null      object
 15  14        0 non-null      object
 16  15        0 non-null      object
 17  16        0 non-null      object
 18  17        0 non-null      object
 19  18        0 non-null      object
 20  19        0 non-null      object
 21  20        0 non-null      object
 22  21        0 non-null      object
 23  22        0 non-null      object
 24  23        0 non-null      object
 25  24        0 non-null      object
 26  25        0 non-null      object
 27  26        0 non-null      object
 28  27        0 non-null      object
 29  28        0 non-null      object
 30  29        0 non-null      object
 31  30        0 non-null      object
 32  31        0 non-null      object
 33  32        0 non-null      object
 34  33        0 non-null      object
 35  34        0 non-null      object
 36  35        0 non-null      object
 37  36        0 non-null      object
 38  37        0 non-null      object
 39  38        0 non-null      object
 40  39        0 non-null      object
 41  40        0 non-null      object
dtypes: object(42)
memory usage: 1.8+ MB

In [8]:
aux2 = aux[aux[4].isna()][["original",0,1,2]]
aux2
## decrease from 5736 to 5589

,original,0,1,2
0,Biognosys|iRT-Kit_WR_fusion,Biognosys,iRT-Kit_WR_fusion,None
2,CON__A2I7N1;CON__A2I7N0,CON__A2I7N1;CON__A2I7N0,None,None
3,CON__A2I7N3,CON__A2I7N3,None,None
4,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,CON__ENSEMBL:ENSBTAP00000001528;sp,Q15811,ITSN1_HUMAN
5,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030,None,None
...,...,...,...,...
5731,sp|Q9Y6Y0|NS1BP_HUMAN,sp,Q9Y6Y0,NS1BP_HUMAN
5732,sp|Q9Y6Y8|S23IP_HUMAN,sp,Q9Y6Y8,S23IP_HUMAN
5733,tr|B3KNS4|B3KNS4_HUMAN,tr,B3KNS4,B3KNS4_HUMAN
5734,tr|Q5TEC6|Q5TEC6_HUMAN,tr,Q5TEC6,Q5TEC6_HUMAN
5735,tr|Q9HB66|Q9HB66_HUMAN,tr,Q9HB66,Q9HB66_HUMAN

In [9]:
base = aux2[~(aux2[1].isna())]
rem = aux2[aux2[1].isna()]

In [10]:
base

,original,0,1,2
0,Biognosys|iRT-Kit_WR_fusion,Biognosys,iRT-Kit_WR_fusion,None
4,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,CON__ENSEMBL:ENSBTAP00000001528;sp,Q15811,ITSN1_HUMAN
26,sp|P02533|K1C14_HUMAN;CON__P02533,sp,P02533,K1C14_HUMAN;CON__P02533
36,sp|P05787|K2C8_HUMAN;CON__P05787,sp,P05787,K2C8_HUMAN;CON__P05787
39,CON__P08727;sp|P08727|K1C19_HUMAN,CON__P08727;sp,P08727,K1C19_HUMAN
...,...,...,...,...
5731,sp|Q9Y6Y0|NS1BP_HUMAN,sp,Q9Y6Y0,NS1BP_HUMAN
5732,sp|Q9Y6Y8|S23IP_HUMAN,sp,Q9Y6Y8,S23IP_HUMAN
5733,tr|B3KNS4|B3KNS4_HUMAN,tr,B3KNS4,B3KNS4_HUMAN
5734,tr|Q5TEC6|Q5TEC6_HUMAN,tr,Q5TEC6,Q5TEC6_HUMAN
5735,tr|Q9HB66|Q9HB66_HUMAN,tr,Q9HB66,Q9HB66_HUMAN

In [30]:
for item in base[0]:
    if len(item)>2:
        print(item)

Biognosys
CON__ENSEMBL:ENSBTAP00000001528;sp
CON__P08727;sp
CON__Q92764;sp
CON__Q9QWL7;sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp
REV__sp

In [33]:
base[base[0].isin(["CON__P08727;sp",
"CON__Q92764;sp",
"CON__Q9QWL7;sp"])]
## first 2 OK
## third OK --> id in col 0 is the same protein but in mouse

,original,0,1,2
39,CON__P08727;sp|P08727|K1C19_HUMAN,CON__P08727;sp,P08727,K1C19_HUMAN
93,CON__Q92764;sp|Q92764|KRT35_HUMAN,CON__Q92764;sp,Q92764,KRT35_HUMAN
96,CON__Q9QWL7;sp|Q04695|K1C17_HUMAN;CON__Q04695,CON__Q9QWL7;sp,Q04695,K1C17_HUMAN;CON__Q04695

In the "base" df, column 1 can be used exclusively, it contains the uniprot ID.

In [11]:
rem2 = rem[0].str.split(";", expand=True)
rem2["original"] = rem["original"]
rem2

,0,1,original
2,CON__A2I7N1,CON__A2I7N0,CON__A2I7N1;CON__A2I7N0
3,CON__A2I7N3,None,CON__A2I7N3
5,CON__ENSEMBL:ENSBTAP00000007350,CON__P01030,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030
6,CON__ENSEMBL:ENSBTAP00000014147,None,CON__ENSEMBL:ENSBTAP00000014147
7,CON__ENSEMBL:ENSBTAP00000016046,None,CON__ENSEMBL:ENSBTAP00000016046
...,...,...,...
91,CON__Q6IFX2,None,CON__Q6IFX2
94,CON__Q95121,None,CON__Q95121
97,CON__Q9TRI1,None,CON__Q9TRI1
98,CON__Q9TTE1,None,CON__Q9TTE1
99,CON__REFSEQ:XP_001252647,None,CON__REFSEQ:XP_001252647

In [36]:
rem2[rem2[1].isna()]

                                  0     1                         original
3                       CON__A2I7N3  None                      CON__A2I7N3
6   CON__ENSEMBL:ENSBTAP00000014147  None  CON__ENSEMBL:ENSBTAP00000014147
7   CON__ENSEMBL:ENSBTAP00000016046  None  CON__ENSEMBL:ENSBTAP00000016046
8   CON__ENSEMBL:ENSBTAP00000018574  None  CON__ENSEMBL:ENSBTAP00000018574
9   CON__ENSEMBL:ENSBTAP00000024146  None  CON__ENSEMBL:ENSBTAP00000024146
..                              ...   ...                              ...
91                      CON__Q6IFX2  None                      CON__Q6IFX2
94                      CON__Q95121  None                      CON__Q95121
97                      CON__Q9TRI1  None                      CON__Q9TRI1
98                      CON__Q9TTE1  None                      CON__Q9TTE1
99         CON__REFSEQ:XP_001252647  None         CON__REFSEQ:XP_001252647

[73 rows x 3 columns]

In [37]:
list(rem2[rem2[1].isna()][0])
## these are all contaminated samples

['CON__A2I7N3',
 'CON__ENSEMBL:ENSBTAP00000014147',
 'CON__ENSEMBL:ENSBTAP00000016046',
 'CON__ENSEMBL:ENSBTAP00000018574',
 'CON__ENSEMBL:ENSBTAP00000024146',
 'CON__ENSEMBL:ENSBTAP00000024462',
 'CON__ENSEMBL:ENSBTAP00000024466',
 'CON__ENSEMBL:ENSBTAP00000031360',
 'CON__ENSEMBL:ENSBTAP00000031900',
 'CON__ENSEMBL:ENSBTAP00000032840',
 'CON__ENSEMBL:ENSBTAP00000034412',
 'CON__ENSEMBL:ENSBTAP00000037665',
 'CON__ENSEMBL:ENSBTAP00000038329',
 'CON__H-INV:HIT000292931',
 'CON__P00735',
 'CON__P00761',
 'CON__P00978',
 'CON__P01966',
 'CON__P02070',
 'CON__P02662',
 'CON__P02663',
 'CON__P02668',
 'CON__P02672',
 'CON__P02754',
 'CON__P02769',
 'CON__P02777',
 'CON__P05784',
 'CON__P06868',
 'CON__P08730-1',
 'CON__P12763',
 'CON__P15497',
 'CON__P17690',
 'CON__P17697',
 'CON__P28800',
 'CON__P34955',
 'CON__P35908',
 'CON__P41361',
 'CON__P50448',
 'CON__P81644',
 'CON__Q03247',
 'CON__Q05443',
 'CON__Q05B55',
 'CON__Q0V8M9',
 'CON__Q0VCM5',
 'CON__Q1RMK2',
 'CON__Q1RMN8',
 'CON__Q28065',
 'CON__Q28085',
 'CON__Q28107',
 'CON__Q2KIU3',
 'CON__Q2KJ62',
 'CON__Q2KJF1',
 'CON__Q2UVX4',
 'CON__Q32PJ2',
 'CON__Q3KUS7',
 'CON__Q3MHN2',
 'CON__Q3SX09',
 'CON__Q3SX14',
 'CON__Q3SX28',
 'CON__Q3SZ57',
 'CON__Q3SZH5',
 'CON__Q3SZR3',
 'CON__Q3SZV7',
 'CON__Q3T052',
 'CON__Q3ZBD7',
 'CON__Q3ZBS7',
 'CON__Q497I4',
 'CON__Q58D62',
 'CON__Q6IFX2',
 'CON__Q95121',
 'CON__Q9TRI1',
 'CON__Q9TTE1',
 'CON__REFSEQ:XP_001252647']

In [39]:
rem2[~rem2[1].isna()]
# first only bos taurus: serpin A3-5 and serpin A3-4
# second: both are bos taurus and different
# third: both are bos taurus
# fourth: both are bos taurus
# fifth: both are bos taurus
# --> all of them can be excluded

,0,1,original
2,CON__A2I7N1,CON__A2I7N0,CON__A2I7N1;CON__A2I7N0
5,CON__ENSEMBL:ENSBTAP00000007350,CON__P01030,CON__ENSEMBL:ENSBTAP00000007350;CON__P01030
23,CON__P01044-1,CON__P01045-1,CON__P01044-1;CON__P01045-1
59,CON__Q0IIK2,CON__Q29443,CON__Q0IIK2;CON__Q29443
77,CON__Q3MHN5,CON__ENSEMBL:ENSBTAP00000018229,CON__Q3MHN5;CON__ENSEMBL:ENSBTAP00000018229

In [40]:
rem2 = rem2[rem2[1].isna()]
rem2

                                  0     1                         original
3                       CON__A2I7N3  None                      CON__A2I7N3
6   CON__ENSEMBL:ENSBTAP00000014147  None  CON__ENSEMBL:ENSBTAP00000014147
7   CON__ENSEMBL:ENSBTAP00000016046  None  CON__ENSEMBL:ENSBTAP00000016046
8   CON__ENSEMBL:ENSBTAP00000018574  None  CON__ENSEMBL:ENSBTAP00000018574
9   CON__ENSEMBL:ENSBTAP00000024146  None  CON__ENSEMBL:ENSBTAP00000024146
..                              ...   ...                              ...
91                      CON__Q6IFX2  None                      CON__Q6IFX2
94                      CON__Q95121  None                      CON__Q95121
97                      CON__Q9TRI1  None                      CON__Q9TRI1
98                      CON__Q9TTE1  None                      CON__Q9TTE1
99         CON__REFSEQ:XP_001252647  None         CON__REFSEQ:XP_001252647

[73 rows x 3 columns]

In [41]:
rem2 = rem2[["original", 0]]
rem2

                           original                                0
3                       CON__A2I7N3                      CON__A2I7N3
6   CON__ENSEMBL:ENSBTAP00000014147  CON__ENSEMBL:ENSBTAP00000014147
7   CON__ENSEMBL:ENSBTAP00000016046  CON__ENSEMBL:ENSBTAP00000016046
8   CON__ENSEMBL:ENSBTAP00000018574  CON__ENSEMBL:ENSBTAP00000018574
9   CON__ENSEMBL:ENSBTAP00000024146  CON__ENSEMBL:ENSBTAP00000024146
..                              ...                              ...
91                      CON__Q6IFX2                      CON__Q6IFX2
94                      CON__Q95121                      CON__Q95121
97                      CON__Q9TRI1                      CON__Q9TRI1
98                      CON__Q9TTE1                      CON__Q9TTE1
99         CON__REFSEQ:XP_001252647         CON__REFSEQ:XP_001252647

[73 rows x 2 columns]

In [12]:
## whole rem2 can be excluded
final = base[["original",1]].rename(columns={"original":"original", 1:0})
final

                                               original                  0
0                           Biognosys|iRT-Kit_WR_fusion  iRT-Kit_WR_fusion
4     CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...             Q15811
26                    sp|P02533|K1C14_HUMAN;CON__P02533             P02533
36                     sp|P05787|K2C8_HUMAN;CON__P05787             P05787
39                    CON__P08727;sp|P08727|K1C19_HUMAN             P08727
...                                                 ...                ...
5731                              sp|Q9Y6Y0|NS1BP_HUMAN             Q9Y6Y0
5732                              sp|Q9Y6Y8|S23IP_HUMAN             Q9Y6Y8
5733                             tr|B3KNS4|B3KNS4_HUMAN             B3KNS4
5734                             tr|Q5TEC6|Q5TEC6_HUMAN             Q5TEC6
5735                             tr|Q9HB66|Q9HB66_HUMAN             Q9HB66

[5511 rows x 2 columns]

In [13]:
for item in final[0]:
    if len(item)>6:
        print(item)

iRT-Kit_WR_fusion
A0A1B0GUA6
A0A024RBG1
A0A0U1RRE5
A0A0U1RRL7

In [15]:
final

                                               original                  0
0                           Biognosys|iRT-Kit_WR_fusion  iRT-Kit_WR_fusion
4     CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...             Q15811
26                    sp|P02533|K1C14_HUMAN;CON__P02533             P02533
36                     sp|P05787|K2C8_HUMAN;CON__P05787             P05787
39                    CON__P08727;sp|P08727|K1C19_HUMAN             P08727
...                                                 ...                ...
5731                              sp|Q9Y6Y0|NS1BP_HUMAN             Q9Y6Y0
5732                              sp|Q9Y6Y8|S23IP_HUMAN             Q9Y6Y8
5733                             tr|B3KNS4|B3KNS4_HUMAN             B3KNS4
5734                             tr|Q5TEC6|Q5TEC6_HUMAN             Q5TEC6
5735                             tr|Q9HB66|Q9HB66_HUMAN             Q9HB66

[5511 rows x 2 columns]

In [16]:
aliases = pd.read_csv("9606.protein.aliases.v12.0.txt", sep="\t")
aliases

,#string_protein_id,alias,source
0,9606.ENSP00000000233,2B6H,Ensembl_PDB
1,9606.ENSP00000000233,2B6H,UniProt_DR_PDB
2,9606.ENSP00000000233,381,Ensembl_HGNC_entrez_id
3,9606.ENSP00000000233,381,KEGG_GENEID
4,9606.ENSP00000000233,381,KEGG_KEGGID_SHORT
...,...,...,...
3889202,9606.ENSP00000501317,regulatory factor X domain containing 2,Ensembl_HGNC_prev_name
3889203,9606.ENSP00000501317,"regulatory factor X, 7",Ensembl_HGNC_prev_name
3889204,9606.ENSP00000501317,regulatory factor X7,Ensembl_HGNC_name
3889205,9606.ENSP00000501317,uc059jng.1,Ensembl_HGNC_ucsc_id
3889206,9606.ENSP00000501317,uc059jng.1,UniProt_DR_UCSC

In [17]:
len(set(final[0]))
## there are peptides "coding" for the same protein --> max value of these should be considered as the abundance of the protein
## 5486 without iRT-Kit_WR_fusion

5487

In [18]:
string_proteins = aliases[aliases["alias"].isin(final[0])][["#string_protein_id","alias"]].drop_duplicates()
string_proteins

           #string_protein_id   alias
84       9606.ENSP00000000233  P84085
262      9606.ENSP00000000412  P20645
448      9606.ENSP00000001008  Q02790
830      9606.ENSP00000002125  Q7L592
958      9606.ENSP00000002165  Q9BTY2
...                       ...     ...
3882930  9606.ENSP00000500409  Q9NRY4
3883854  9606.ENSP00000500633  Q9HBU6
3887041  9606.ENSP00000501135  Q9BTM9
3887327  9606.ENSP00000501146  Q14541
3887503  9606.ENSP00000501150  P42338

[5501 rows x 2 columns]

In [19]:
len(set(string_proteins["alias"])), len(set(string_proteins["#string_protein_id"]))

(5472, 5500)

In [20]:
string_info = pd.read_csv("9606.protein.info.v12.0.txt", sep="\t")
string_info.head()

,#string_protein_id,preferred_name,protein_size,annotation
0,9606.ENSP00000000233,ARF5,180,ADP-ribosylation factor 5; GTP-binding protein...
1,9606.ENSP00000000412,M6PR,277,Cation-dependent mannose-6-phosphate receptor;...
2,9606.ENSP00000001008,FKBP4,459,"Peptidyl-prolyl cis-trans isomerase FKBP4, N-t..."
3,9606.ENSP00000001146,CYP26B1,512,Cytochrome P450 26B1; Involved in the metaboli...
4,9606.ENSP00000002125,NDUFAF7,441,"Protein arginine methyltransferase NDUFAF7, mi..."

In [21]:
(string_proteins.groupby("#string_protein_id").count())[string_proteins.groupby("#string_protein_id").count()["alias"]>1]

                      alias
#string_protein_id
9606.ENSP00000338352      2

In [22]:
string_proteins[string_proteins["#string_protein_id"]=="9606.ENSP00000338352"]
## second one is the good one --> remove: 1259228

           #string_protein_id       alias
1259228  9606.ENSP00000338352  A0A024RBG1
1259382  9606.ENSP00000338352      Q9NZJ9

In [23]:
string_info[string_info["#string_protein_id"]=="9606.ENSP00000338352"]

,#string_protein_id,preferred_name,protein_size,annotation
7866,9606.ENSP00000338352,NUDT4,181,Diphosphoinositol polyphosphate phosphohydrola...

In [24]:
(string_proteins.groupby("alias").count())[string_proteins.groupby("alias").count()["#string_protein_id"]>1]

            #string_protein_id
alias
A0A024RBG1                   2
P23610                       3
P43243                       2
P62805                      14
P69905                       2
Q15813                       2
Q16637                       2
Q6ZSZ5                       2
Q8TEA8                       2
Q96BK5                       2
Q9H3K6                       2
Q9H6U8                       2
Q9NR28                       2
Q9UBX3                       2
Q9UG63                       2
Q9ULR0                       2

In [146]:
string_proteins.to_excel("protein_string_mapping.xlsx")

In [25]:
string_proteins = pd.read_excel("protein_string_mapping.xlsx", index_col=0)

In [26]:
string_proteins

           #string_protein_id       alias
3775574  9606.ENSP00000492425  A0A024RBG1
3753430  9606.ENSP00000489583  A0A0U1RRE5
3753602  9606.ENSP00000489588  A0A0U1RRL7
3757990  9606.ENSP00000490029  A0A1B0GUA6
730917   9606.ENSP00000295971      A0AV96
...                       ...         ...
3707132  9606.ENSP00000483313      Q9Y6W5
2845731  9606.ENSP00000380763      Q9Y6X9
2239290  9606.ENSP00000356468      Q9Y6Y0
2290728  9606.ENSP00000358071      Q9Y6Y8
950406   9606.ENSP00000312081      Q8TE77

[5472 rows x 2 columns]

In [27]:
len(set(string_proteins["alias"])), len(set(string_proteins["#string_protein_id"]))

(5472, 5472)

In [28]:
final

                                               original                  0
0                           Biognosys|iRT-Kit_WR_fusion  iRT-Kit_WR_fusion
4     CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...             Q15811
26                    sp|P02533|K1C14_HUMAN;CON__P02533             P02533
36                     sp|P05787|K2C8_HUMAN;CON__P05787             P05787
39                    CON__P08727;sp|P08727|K1C19_HUMAN             P08727
...                                                 ...                ...
5731                              sp|Q9Y6Y0|NS1BP_HUMAN             Q9Y6Y0
5732                              sp|Q9Y6Y8|S23IP_HUMAN             Q9Y6Y8
5733                             tr|B3KNS4|B3KNS4_HUMAN             B3KNS4
5734                             tr|Q5TEC6|Q5TEC6_HUMAN             Q5TEC6
5735                             tr|Q9HB66|Q9HB66_HUMAN             Q9HB66

[5511 rows x 2 columns]

In [29]:
for item in final[0]:
    if "-" in item:
        print(item)

iRT-Kit_WR_fusion

The saved mapping is final!

In [32]:
final_final = final.merge(string_proteins, left_on=0, right_on="alias")
final_final

,original,0,#string_protein_id,alias
0,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,Q15811,9606.ENSP00000370719,Q15811
1,sp|P02533|K1C14_HUMAN;CON__P02533,P02533,9606.ENSP00000167586,P02533
2,sp|P05787|K2C8_HUMAN;CON__P05787,P05787,9606.ENSP00000449404,P05787
3,CON__P08727;sp|P08727|K1C19_HUMAN,P08727,9606.ENSP00000355124,P08727
4,sp|P08779|K1C16_HUMAN;CON__P08779,P08779,9606.ENSP00000301653,P08779
...,...,...,...,...
5491,sp|Q9Y6Y0|NS1BP_HUMAN,Q9Y6Y0,9606.ENSP00000356468,Q9Y6Y0
5492,sp|Q9Y6Y8|S23IP_HUMAN,Q9Y6Y8,9606.ENSP00000358071,Q9Y6Y8
5493,tr|B3KNS4|B3KNS4_HUMAN,B3KNS4,9606.ENSP00000489180,B3KNS4
5494,tr|Q5TEC6|Q5TEC6_HUMAN,Q5TEC6,9606.ENSP00000499501,Q5TEC6
5495,tr|Q9HB66|Q9HB66_HUMAN,Q9HB66,9606.ENSP00000497510,Q9HB66

In [33]:
len(set(final_final["original"])), len(set(final_final[0])), len(set(final_final["alias"])), len(set(final_final["#string_protein_id"]))

(5496, 5472, 5472, 5472)

In [34]:
(final_final.groupby("alias").count())[final_final.groupby("alias").count()[0]>1]

        original  0  #string_protein_id
alias
O00629         2  2                   2
O14772         2  2                   2
O60645         2  2                   2
O95347         2  2                   2
Q07666         2  2                   2
Q13045         2  2                   2
Q14573         2  2                   2
Q14669         2  2                   2
Q15631         2  2                   2
Q15643         2  2                   2
Q6I9Y2         2  2                   2
Q8NF91         2  2                   2
Q8TD57         2  2                   2
Q8WZ42         2  2                   2
Q969S9         2  2                   2
Q96HY6         2  2                   2
Q99575         2  2                   2
Q99986         2  2                   2
Q99996         2  2                   2
Q9C037         2  2                   2
Q9H2G2         2  2                   2
Q9NPB8         2  2                   2
Q9NVU7         2  2                   2
Q9UPN9         2  2                   2

In [35]:
final_final[final_final["alias"]=="O14772"]

                     original       0    #string_protein_id   alias
20  REV__sp|O14772|FPGT_HUMAN  O14772  9606.ENSP00000359935  O14772
21       sp|O14772|FPGT_HUMAN  O14772  9606.ENSP00000359935  O14772

In [36]:
data[data["Protein IDs"].isin(["REV__sp|O14772|FPGT_HUMAN", "sp|O14772|FPGT_HUMAN"])]

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9
103,REV__sp|O14772|FPGT_HUMAN,REV__sp|O14772|FPGT_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,sp|O14772|FPGT_HUMAN,sp|O14772|FPGT_HUMAN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
aux_index = (final_final.groupby("alias").count())[final_final.groupby("alias").count()[0]>1].index

In [38]:
aux_df = final_final[final_final["alias"].isin(aux_index)]
aux_df

                      original       0    #string_protein_id   alias
17   REV__sp|O00629|IMA3_HUMAN  O00629  9606.ENSP00000334373  O00629
18        sp|O00629|IMA3_HUMAN  O00629  9606.ENSP00000334373  O00629
20   REV__sp|O14772|FPGT_HUMAN  O14772  9606.ENSP00000359935  O14772
21        sp|O14772|FPGT_HUMAN  O14772  9606.ENSP00000359935  O14772
22  REV__sp|O60645|EXOC3_HUMAN  O60645  9606.ENSP00000425587  O60645
23       sp|O60645|EXOC3_HUMAN  O60645  9606.ENSP00000425587  O60645
28   REV__sp|O95347|SMC2_HUMAN  O95347  9606.ENSP00000286398  O95347
29        sp|O95347|SMC2_HUMAN  O95347  9606.ENSP00000286398  O95347
34  REV__sp|Q07666|KHDR1_HUMAN  Q07666  9606.ENSP00000313829  Q07666
35       sp|Q07666|KHDR1_HUMAN  Q07666  9606.ENSP00000313829  Q07666
36   REV__sp|Q13045|FLII_HUMAN  Q13045  9606.ENSP00000324573  Q13045
37        sp|Q13045|FLII_HUMAN  Q13045  9606.ENSP00000324573  Q13045
38  REV__sp|Q14573|ITPR3_HUMAN  Q14573  9606.ENSP00000363435  Q14573
39       sp|Q14573|ITPR3_HUMAN  Q14573  9606.ENSP00000363435  Q14573
40  REV__sp|Q14669|TRIPC_HUMAN  Q14669  9606.ENSP00000373696  Q14669
41       sp|Q14669|TRIPC_HUMAN  Q14669  9606.ENSP00000373696  Q14669
42    REV__sp|Q15631|TSN_HUMAN  Q15631  9606.ENSP00000374332  Q15631
43         sp|Q15631|TSN_HUMAN  Q15631  9606.ENSP00000374332  Q15631
44  REV__sp|Q15643|TRIPB_HUMAN  Q15643  9606.ENSP00000267622  Q15643
45       sp|Q15643|TRIPB_HUMAN  Q15643  9606.ENSP00000267622  Q15643
50  REV__sp|Q6I9Y2|THOC7_HUMAN  Q6I9Y2  9606.ENSP00000295899  Q6I9Y2
51       sp|Q6I9Y2|THOC7_HUMAN  Q6I9Y2  9606.ENSP00000295899  Q6I9Y2
60  REV__sp|Q8NF91|SYNE1_HUMAN  Q8NF91  9606.ENSP00000356224  Q8NF91
61       sp|Q8NF91|SYNE1_HUMAN  Q8NF91  9606.ENSP00000356224  Q8NF91
63   REV__sp|Q8TD57|DYH3_HUMAN  Q8TD57  9606.ENSP00000261383  Q8TD57
64        sp|Q8TD57|DYH3_HUMAN  Q8TD57  9606.ENSP00000261383  Q8TD57
67  REV__sp|Q8WZ42|TITIN_HUMAN  Q8WZ42  9606.ENSP00000467141  Q8WZ42
68       sp|Q8WZ42|TITIN_HUMAN  Q8WZ42  9606.ENSP00000467141  Q8WZ42
70  REV__sp|Q969S9|RRF2M_HUMAN  Q969S9  9606.ENSP00000427004  Q969S9
71       sp|Q969S9|RRF2M_HUMAN  Q969S9  9606.ENSP00000427004  Q969S9
73  REV__sp|Q96HY6|DDRGK_HUMAN  Q96HY6  9606.ENSP00000346483  Q96HY6
74       sp|Q96HY6|DDRGK_HUMAN  Q96HY6  9606.ENSP00000346483  Q96HY6
77   REV__sp|Q99575|POP1_HUMAN  Q99575  9606.ENSP00000385787  Q99575
78        sp|Q99575|POP1_HUMAN  Q99575  9606.ENSP00000385787  Q99575
81   REV__sp|Q99986|VRK1_HUMAN  Q99986  9606.ENSP00000216639  Q99986
82        sp|Q99986|VRK1_HUMAN  Q99986  9606.ENSP00000216639  Q99986
83  REV__sp|Q99996|AKAP9_HUMAN  Q99996  9606.ENSP00000348573  Q99996
84       sp|Q99996|AKAP9_HUMAN  Q99996  9606.ENSP00000348573  Q99996
87  REV__sp|Q9C037|TRIM4_HUMAN  Q9C037  9606.ENSP00000348216  Q9C037
88       sp|Q9C037|TRIM4_HUMAN  Q9C037  9606.ENSP00000348216  Q9C037
89    REV__sp|Q9H2G2|SLK_HUMAN  Q9H2G2  9606.ENSP00000358770  Q9H2G2
90         sp|Q9H2G2|SLK_HUMAN  Q9H2G2  9606.ENSP00000358770  Q9H2G2
91  REV__sp|Q9NPB8|GPCP1_HUMAN  Q9NPB8  9606.ENSP00000368305  Q9NPB8
92       sp|Q9NPB8|GPCP1_HUMAN  Q9NPB8  9606.ENSP00000368305  Q9NPB8
93   REV__sp|Q9NVU7|SDA1_HUMAN  Q9NVU7  9606.ENSP00000348596  Q9NVU7
94        sp|Q9NVU7|SDA1_HUMAN  Q9NVU7  9606.ENSP00000348596  Q9NVU7
98  REV__sp|Q9UPN9|TRI33_HUMAN  Q9UPN9  9606.ENSP00000351250  Q9UPN9
99       sp|Q9UPN9|TRI33_HUMAN  Q9UPN9  9606.ENSP00000351250  Q9UPN9

In [39]:
data[data["Majority protein IDs"].isin(aux_df["original"])]

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9
101,REV__sp|O00629|IMA3_HUMAN,REV__sp|O00629|IMA3_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,REV__sp|O14772|FPGT_HUMAN,REV__sp|O14772|FPGT_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,REV__sp|O60645|EXOC3_HUMAN,REV__sp|O60645|EXOC3_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,REV__sp|O95347|SMC2_HUMAN,REV__sp|O95347|SMC2_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,REV__sp|Q07666|KHDR1_HUMAN,REV__sp|Q07666|KHDR1_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,REV__sp|Q13045|FLII_HUMAN,REV__sp|Q13045|FLII_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,REV__sp|Q14573|ITPR3_HUMAN,REV__sp|Q14573|ITPR3_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,REV__sp|Q14669|TRIPC_HUMAN,REV__sp|Q14669|TRIPC_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,REV__sp|Q15631|TSN_HUMAN,REV__sp|Q15631|TSN_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,REV__sp|Q15643|TRIPB_HUMAN,REV__sp|Q15643|TRIPB_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,REV__sp|Q6I9Y2|THOC7_HUMAN,REV__sp|Q6I9Y2|THOC7_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,REV__sp|Q8NF91|SYNE1_HUMAN,REV__sp|Q8NF91|SYNE1_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,REV__sp|Q8TD57|DYH3_HUMAN,REV__sp|Q8TD57|DYH3_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,REV__sp|Q8WZ42|TITIN_HUMAN,REV__sp|Q8WZ42|TITIN_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,REV__sp|Q969S9|RRF2M_HUMAN,REV__sp|Q969S9|RRF2M_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,REV__sp|Q96HY6|DDRGK_HUMAN,REV__sp|Q96HY6|DDRGK_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,REV__sp|Q99575|POP1_HUMAN,REV__sp|Q99575|POP1_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,REV__sp|Q99986|VRK1_HUMAN,REV__sp|Q99986|VRK1_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,REV__sp|Q99996|AKAP9_HUMAN,REV__sp|Q99996|AKAP9_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,REV__sp|Q9C037|TRIM4_HUMAN,REV__sp|Q9C037|TRIM4_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,REV__sp|Q9H2G2|SLK_HUMAN,REV__sp|Q9H2G2|SLK_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,REV__sp|Q9NPB8|GPCP1_HUMAN,REV__sp|Q9NPB8|GPCP1_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,REV__sp|Q9NVU7|SDA1_HUMAN,REV__sp|Q9NVU7|SDA1_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,REV__sp|Q9UPN9|TRI33_HUMAN,REV__sp|Q9UPN9|TRI33_HUMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,sp|O00629|IMA3_HUMAN,sp|O00629|IMA3_HUMAN,60342000.0,43629000.0,48597000.0,39365000.0,38728000.0,42612000.0,34902000.0,44914000.0
323,sp|O14772|FPGT_HUMAN,sp|O14772|FPGT_HUMAN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
554,sp|O60645|EXOC3_HUMAN,sp|O60645|EXOC3_HUMAN,4008800.0,3166900.0,1938800.0,2140200.0,1974800.0,1990200.0,1709500.0,2607200.0
793,sp|O95347|SMC2_HUMAN,sp|O95347|SMC2_HUMAN,6080600.0,7031200.0,7087800.0,7719400.0,9870200.0,6049500.0,4618100.0,4174100.0
2379,sp|Q07666|KHDR1_HUMAN;sp|Q5VWX1|KHDR2_HUMAN;sp...,sp|Q07666|KHDR1_HUMAN,121210000.0,133960000.0,110450000.0,111070000.0,84274000.0,86512000.0,61565000.0,107740000.0
2469,sp|Q13045|FLII_HUMAN,sp|Q13045|FLII_HUMAN,14161000.0,12556000.0,7955800.0,6700000.0,7087600.0,7562100.0,7462600.0,7591900.0
2662,sp|Q14573|ITPR3_HUMAN,sp|Q14573|ITPR3_HUMAN,7374800.0,6300900.0,4813900.0,4652300.0,5102600.0,5633200.0,5317100.0,5978800.0
2668,sp|Q14669|TRIPC_HUMAN,sp|Q14669|TRIPC_HUMAN,2981800.0,4420300.0,2219600.0,2292100.0,2279600.0,1860500.0,1599000.0,1535200.0
2798,sp|Q15631|TSN_HUMAN,sp|Q15631|TSN_HUMAN,73256000.0,54811000.0,49111000.0,46394000.0,40364000.0,51890000.0,57070000.0,57246000.0
2802,sp|Q15643|TRIPB_HUMAN,sp|Q15643|TRIPB_HUMAN,548470.0,604600.0,263430.0,593890.0,349310.0,101270.0,264990.0,85409.0
3121,sp|Q6I9Y2|THOC7_HUMAN,sp|Q6I9Y2|THOC7_HUMAN,6158300.0,3670500.0,0.0,8517300.0,4391300.0,4893400.0,1884900.0,1949300.0
3685,sp|Q8NF91|SYNE1_HUMAN,sp|Q8NF91|SYNE1_HUMAN,1150700.0,974690.0,1245900.0,239550.0,1072200.0,1093900.0,1129400.0,1130500.0
3758,sp|Q8TD57|DYH3_HUMAN,sp|Q8TD57|DYH3_HUMAN,768870.0,0.0,663860.0,0.0,0.0,0.0,637570.0,680850.0
3862,sp|Q8WZ42|TITIN_HUMAN,sp|Q8WZ42|TITIN_HUMAN,295080.0,13969.0,226080.0,57574.0,122980.0,134310.0,75571.0,60772.0
3975,sp|Q969S9|RRF2M_HUMAN,sp|Q969S9|RRF2M_HUMAN,0.0,0.0,175840.0,0.0,0.0,515710.0,794580.0,179760.0
4154,sp|Q96HY6|DDRGK_HUMAN,sp|Q96HY6|DDRGK_HUMAN,15372000.0,7121300.0,10650000.0,10458000.0,10996000.0,3372100.0,15320000.0,9354200.0
4321,sp|Q99575|POP1_HUMAN,sp|Q99575|POP1_HUMAN,6052800.0,9386400.0,8523900.0,7573000.0,8171900.0,5964800.0,4074100.0,7412500.0
4364,sp|Q99986|VRK1_HUMAN,sp|Q99986|VRK1_HUMAN,2187300.0,3527500.0,3211700.0,4482600.0,3250500.0,4674100.0,5135900.0,3026400.0
4365,sp|Q99996|AKAP9_HUMAN,sp|Q99996|AKAP9_HUMAN,19621.0,0.0,0.0,0.0,80040.0,87327.0,111580.0,47881.0
4596,sp|Q9C037|TRIM4_HUMAN,sp|Q9C037|TRIM4_HUMAN,0.0,428490.0,1506800.0,1559600.0,459000.0,0.0,1659100.0,717870.0
4689,sp|Q9H2G2|SLK_HUMAN,sp|Q9H2G2|SLK_HUMAN,15571000.0,16504000.0,10821000.0,10157000.0,12696000.0,7294900.0,9163800.0,8092600.0
4885,sp|Q9NPB8|GPCP1_HUMAN,sp|Q9NPB8|GPCP1_HUMAN,0.0,0.0,0.0,327830.0,246370.0,0.0,0.0,232880.0
5043,sp|Q9NVU7|SDA1_HUMAN,sp|Q9NVU7|SDA1_HUMAN,1191400.0,951920.0,1395700.0,2085000.0,1165300.0,388540.0,606590.0,383640.0
5461,sp|Q9UPN9|TRI33_HUMAN,sp|Q9UPN9|TRI33_HUMAN,190220.0,768820.0,202490.0,198960.0,0.0,330150.0,174100.0,132770.0

Rows with "REV__" and "CON__P35908" can be deleted.

In [40]:
for item in data["Majority protein IDs"]:
    if "CON__P35908" in item:
        print(item)

CON__P35908

In [41]:
data[data["Majority protein IDs"]=="CON__P35908"]

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9
52,CON__P35908;sp|Q7Z794|K2C1B_HUMAN;CON__Q7Z794;...,CON__P35908,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
data[data["Majority protein IDs"]=="sp|P35908|K22E_HUMAN"]

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9
1593,sp|P35908|K22E_HUMAN,sp|P35908|K22E_HUMAN,23340000.0,18572000.0,39831000.0,65178000.0,26800000.0,15811000.0,12395000.0,4189400.0

In [43]:
indices_to_delete = []
for item in aux_df["original"]:
    if ("REV" in item)or("CON" in item):
        indices_to_delete.append(item)
        
len(indices_to_delete)

24

In [44]:
to_keep = list(set(final_final["original"])-set(indices_to_delete))
final_final = final_final[final_final["original"].isin(to_keep)]
final_final

,original,0,#string_protein_id,alias
0,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,Q15811,9606.ENSP00000370719,Q15811
1,sp|P02533|K1C14_HUMAN;CON__P02533,P02533,9606.ENSP00000167586,P02533
2,sp|P05787|K2C8_HUMAN;CON__P05787,P05787,9606.ENSP00000449404,P05787
3,CON__P08727;sp|P08727|K1C19_HUMAN,P08727,9606.ENSP00000355124,P08727
4,sp|P08779|K1C16_HUMAN;CON__P08779,P08779,9606.ENSP00000301653,P08779
...,...,...,...,...
5491,sp|Q9Y6Y0|NS1BP_HUMAN,Q9Y6Y0,9606.ENSP00000356468,Q9Y6Y0
5492,sp|Q9Y6Y8|S23IP_HUMAN,Q9Y6Y8,9606.ENSP00000358071,Q9Y6Y8
5493,tr|B3KNS4|B3KNS4_HUMAN,B3KNS4,9606.ENSP00000489180,B3KNS4
5494,tr|Q5TEC6|Q5TEC6_HUMAN,Q5TEC6,9606.ENSP00000499501,Q5TEC6
5495,tr|Q9HB66|Q9HB66_HUMAN,Q9HB66,9606.ENSP00000497510,Q9HB66

In [45]:
len(set(final_final["original"])), len(set(final_final[0])), len(set(final_final["alias"])), len(set(final_final["#string_protein_id"]))

(5472, 5472, 5472, 5472)

In [199]:
final_final.to_csv("protein_string_mapping_final.csv")

In [46]:
data2 = data.merge(final_final[["original","#string_protein_id", "alias"]], left_on="Majority protein IDs", right_on="original")

In [47]:
data2

,Protein IDs,Majority protein IDs,g-1,g-3,g-4,g-5,g-6,g-7,g-8,g-9,original,#string_protein_id,alias
0,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,CON__ENSEMBL:ENSBTAP00000001528;sp|Q15811|ITSN...,9606.ENSP00000370719,Q15811
1,sp|P02533|K1C14_HUMAN;CON__P02533;CON__Q61782,sp|P02533|K1C14_HUMAN;CON__P02533,6.370200e+05,5.010300e+05,2.091400e+06,7.221000e+06,2.897200e+06,3.121100e+05,0.000000e+00,0.000000e+00,sp|P02533|K1C14_HUMAN;CON__P02533,9606.ENSP00000167586,P02533
2,sp|P05787|K2C8_HUMAN;CON__P05787;CON__Q9H552;C...,sp|P05787|K2C8_HUMAN;CON__P05787,4.703500e+09,4.504900e+09,3.976400e+09,4.033000e+09,3.973900e+09,3.970800e+09,3.727000e+09,3.666100e+09,sp|P05787|K2C8_HUMAN;CON__P05787,9606.ENSP00000449404,P05787
3,CON__P08727;sp|P08727|K1C19_HUMAN;CON__P19001,CON__P08727;sp|P08727|K1C19_HUMAN,8.483700e+08,7.295500e+08,5.907200e+08,6.845700e+08,5.975200e+08,6.104000e+08,6.023800e+08,5.939400e+08,CON__P08727;sp|P08727|K1C19_HUMAN,9606.ENSP00000355124,P08727
4,sp|P08779|K1C16_HUMAN;CON__P08779;CON__Q9Z2K1;...,sp|P08779|K1C16_HUMAN;CON__P08779,0.000000e+00,3.136000e+05,7.553500e+05,1.012600e+06,1.005500e+06,0.000000e+00,0.000000e+00,0.000000e+00,sp|P08779|K1C16_HUMAN;CON__P08779,9606.ENSP00000301653,P08779
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5467,sp|Q9Y6Y0|NS1BP_HUMAN,sp|Q9Y6Y0|NS1BP_HUMAN,5.639500e+05,7.146100e+05,0.000000e+00,8.943900e+05,6.426200e+05,0.000000e+00,0.000000e+00,0.000000e+00,sp|Q9Y6Y0|NS1BP_HUMAN,9606.ENSP00000356468,Q9Y6Y0
5468,sp|Q9Y6Y8|S23IP_HUMAN,sp|Q9Y6Y8|S23IP_HUMAN,5.718900e+06,5.683100e+06,7.192000e+06,4.491700e+06,4.680500e+06,5.076900e+06,3.266500e+06,7.789400e+06,sp|Q9Y6Y8|S23IP_HUMAN,9606.ENSP00000358071,Q9Y6Y8
5469,tr|B3KNS4|B3KNS4_HUMAN,tr|B3KNS4|B3KNS4_HUMAN,3.499400e+07,4.555700e+07,3.257200e+07,3.982800e+07,3.325000e+07,2.231400e+07,3.396600e+07,3.249400e+07,tr|B3KNS4|B3KNS4_HUMAN,9606.ENSP00000489180,B3KNS4
5470,tr|Q5TEC6|Q5TEC6_HUMAN,tr|Q5TEC6|Q5TEC6_HUMAN,3.716700e+09,2.771600e+09,2.120100e+09,2.258400e+09,1.576100e+09,2.463900e+09,1.716500e+09,2.386800e+09,tr|Q5TEC6|Q5TEC6_HUMAN,9606.ENSP00000499501,Q5TEC6
5471,tr|Q9HB66|Q9HB66_HUMAN,tr|Q9HB66|Q9HB66_HUMAN,2.648000e+07,0.000000e+00,1.675700e+07,0.000000e+00,1.860600e+07,1.600200e+07,2.055600e+07,2.148100e+07,tr|Q9HB66|Q9HB66_HUMAN,9606.ENSP00000497510,Q9HB66

In [206]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5472 entries, 0 to 5471
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Protein IDs           5472 non-null   object
 1   Majority protein IDs  5472 non-null   object
 2   g-1                   5436 non-null   float64
 3   g-3                   5436 non-null   float64
 4   g-4                   5436 non-null   float64
 5   g-5                   5436 non-null   float64
 6   g-6                   5436 non-null   float64
 7   g-7                   5436 non-null   float64
 8   g-8                   5436 non-null   float64
 9   g-9                   5436 non-null   float64
 10  original              5472 non-null   object
 11  #string_protein_id    5472 non-null   object
 12  alias                 5472 non-null   object
dtypes: float64(8), object(5)
memory usage: 598.5+ KB

In [208]:
data2.to_csv("data/1-9DDA_mapped.csv", index=False)

___

# Embryogenesis data:

In [2]:
data_prot = pd.read_csv("data/proteinGroups.txt", sep="\t")
data_prot

/tmp/ipykernel_822452/3359043052.py:1: DtypeWarning: Columns (484,485) have mixed types. Specify dtype option on import or set low_memory=False.
  data_prot = pd.read_csv("data/proteinGroups.txt", sep="\t")

,Protein IDs,Majority protein IDs,Peptide counts (all),Peptide counts (razor+unique),Peptide counts (unique),Fasta headers,Number of proteins,Peptides,Razor + unique peptides,Unique peptides,...,Potential contaminant,id,Peptide IDs,Peptide is razor,Mod. peptide IDs,Evidence IDs,MS/MS IDs,Best MS/MS,Oxidation (M) site IDs,Oxidation (M) site positions
0,CON__ENSEMBL:ENSBTAP00000025008,CON__ENSEMBL:ENSBTAP00000025008,8,2,2,>ENSEMBL:ENSBTAP00000025008 (Bos taurus) hypot...,1,8,2,2,...,+,0,5445;8766;27892;27893;47024;51853;56098;120569,True;True;False;False;False;False;False;False,5807;9410;29646;29647;50112;55211;55212;59723;...,187965;301773;301774;912722;912723;912724;9127...,160597;259457;259458;771913;771914;771915;7719...,160597;259458;772272;772276;1358402;1498161;16...,0,343
1,CON__ENSEMBL:ENSBTAP00000038253,CON__ENSEMBL:ENSBTAP00000038253,13,3,2,>ENSEMBL:ENSBTAP00000038253 (Bos taurus) 63 kD...,1,13,3,2,...,+,1,7078;16391;26943;54733;55519;63100;76396;76397...,False;False;False;False;False;False;True;True;...,7623;17409;17410;28586;58259;59094;67086;67087...,244554;244555;244556;244557;244558;244559;2445...,210113;210114;210115;210116;210117;210118;2101...,210130;461910;744327;1581095;1604065;1814430;2...,1,465
2,CON__O43790;CON__Q14533,CON__O43790;CON__Q14533,13;11,12;10,3;1,">O43790 SWISS-PROT:O43790 Keratin, type II cut...",2,13,12,3,...,+,2,1566;7074;7751;24131;24222;24223;26941;31964;5...,True;True;True;True;True;True;False;True;True;...,1666;7619;8331;25615;25709;25710;28584;33966;5...,55849;244531;267052;267053;783583;783584;78358...,49998;210094;229314;229315;661289;661290;66360...,49998;210094;229315;661289;663607;663608;74413...,NaN,NaN
3,CON__P00761,CON__P00761,8,8,7,>P00761 SWISS-PROT:P00761|TRYP_PIG Trypsin - S...,1,8,8,7,...,+,3,44075;44076;58867;67546;76217;97115;107943;108124,True;True;True;True;True;True;True;True,46897;46898;46899;62611;71843;82152;104315;115...,1490467;1490468;1490469;1490470;1490471;149047...,1268104;1268105;1268106;1268107;1268108;126810...,1268297;1268395;1690789;1932037;2184583;269842...,2,94
4,CON__P02533,CON__P02533,28,24,5,>P02533 SWISS-PROT:P02533 Tax_Id=9606 Gene_Sym...,1,28,24,5,...,+,4,1327;1328;4506;6541;7466;7467;9627;10968;23303...,True;True;True;True;True;True;True;True;True;T...,1406;1407;1408;4802;7051;8028;8029;10321;11721...,47662;47663;47664;47665;47666;47667;47668;4766...,42811;42812;42813;42814;42815;42816;42817;1326...,42813;42817;132663;196697;222431;222454;290799...,3;4;5,119;237;287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7382,YPR139C,YPR139C,1,1,1,>YPR139C pep:known chromosome:R64-1-1:XVI:8131...,1,1,1,1,...,NaN,7382,70956,True,75692,2404324;2404325,2033455;2033456,2033455,8211,1
7383,YPR149W,YPR149W,3,3,3,>YPR149W pep:known chromosome:R64-1-1:XVI:8299...,1,3,3,3,...,NaN,7383,3177;88865;103437,True;True;True,3393;95513;111034,109099;2959069;3427333;3427334,94286;2480988;2874985,94286;2480988;2874985,NaN,NaN
7384,YPR160W,YPR160W,15,13,13,>YPR160W pep:known chromosome:R64-1-1:XVI:8613...,1,15,13,13,...,NaN,7384,1763;4417;14484;15781;26253;29391;70366;74722;...,True;True;True;True;True;True;True;True;True;T...,1872;4708;15411;16764;27852;31232;74874;80582;...,60995;152805;485692;485693;485694;485695;48569...,53995;130215;415309;445585;723388;723389;72339...,53995;130215;415309;445585;723390;816979;20149...,NaN,NaN
7385,YPR183W,YPR183W,9,9,9,>YPR183W pep:known chromosome:R64-1-1:XVI:9007...,1,9,9,9,...,NaN,7385,40852;58040;58189;64171;80390;92965;107575;110...,True;True;True;True;True;True;True;True;True,43471;61738;61901;68298;86616;99856;115485;118...,1372366;1372367;1372368;1372369;1372370;137237...,1164843;1164844;1164845;1164846;1164847;166664...,1164844;1666643;1670496;1842181;2291233;258760...,NaN,NaN
7386,YPR191W,YPR191W,22,22,22,>YPR191W pep:known chromosome:R64-1-1:XVI:9193...,1,22,22,22,...,NaN,7386,7900;12392;14067;14767;14768;22463;26337;27628...,True;True;True;True;True;True;True;True;True;T...,8491;13215;14953;15709;15710;23862;27941;29374...,271786;271787;271788;271789;271790;271791;2717...,233136;233137;233138;233139;233140;233141;3600...,233138;360083;402909;422830;422832;616955;7264...,NaN,NaN

In [4]:
list(data_prot.columns)

['Protein IDs',
 'Majority protein IDs',
 'Peptide counts (all)',
 'Peptide counts (razor+unique)',
 'Peptide counts (unique)',
 'Fasta headers',
 'Number of proteins',
 'Peptides',
 'Razor + unique peptides',
 'Unique peptides',
 'Peptides 00h_1',
 'Peptides 00h_2',
 'Peptides 00h_3',
 'Peptides 00h_4',
 'Peptides 01h_1',
 'Peptides 01h_2',
 'Peptides 01h_3',
 'Peptides 01h_4',
 'Peptides 02h_1',
 'Peptides 02h_2',
 'Peptides 02h_3',
 'Peptides 02h_4',
 'Peptides 03h_1',
 'Peptides 03h_2',
 'Peptides 03h_3',
 'Peptides 03h_4',
 'Peptides 04h_1',
 'Peptides 04h_2',
 'Peptides 04h_3',
 'Peptides 04h_4',
 'Peptides 05h_1',
 'Peptides 05h_2',
 'Peptides 05h_3',
 'Peptides 05h_4',
 'Peptides 06h_1',
 'Peptides 06h_2',
 'Peptides 06h_3',
 'Peptides 06h_4',
 'Peptides 08h_1',
 'Peptides 08h_2',
 'Peptides 08h_3',
 'Peptides 08h_4',
 'Peptides 10h_1',
 'Peptides 10h_2',
 'Peptides 10h_3',
 'Peptides 10h_4',
 'Peptides 12h_1',
 'Peptides 12h_2',
 'Peptides 12h_3',
 'Peptides 12h_4',
 'Peptides 14h_1',
 'Peptides 14h_2',
 'Peptides 14h_3',
 'Peptides 14h_4',
 'Peptides 16h_1',
 'Peptides 16h_2',
 'Peptides 16h_3',
 'Peptides 16h_4',
 'Peptides 18h_1',
 'Peptides 18h_2',
 'Peptides 18h_3',
 'Peptides 18h_4',
 'Peptides 20h_1',
 'Peptides 20h_2',
 'Peptides 20h_3',
 'Peptides 20h_4',
 'Razor + unique peptides 00h_1',
 'Razor + unique peptides 00h_2',
 'Razor + unique peptides 00h_3',
 'Razor + unique peptides 00h_4',
 'Razor + unique peptides 01h_1',
 'Razor + unique peptides 01h_2',
 'Razor + unique peptides 01h_3',
 'Razor + unique peptides 01h_4',
 'Razor + unique peptides 02h_1',
 'Razor + unique peptides 02h_2',
 'Razor + unique peptides 02h_3',
 'Razor + unique peptides 02h_4',
 'Razor + unique peptides 03h_1',
 'Razor + unique peptides 03h_2',
 'Razor + unique peptides 03h_3',
 'Razor + unique peptides 03h_4',
 'Razor + unique peptides 04h_1',
 'Razor + unique peptides 04h_2',
 'Razor + unique peptides 04h_3',
 'Razor + unique peptides 04h_4',
 'Razor + unique peptides 05h_1',
 'Razor + unique peptides 05h_2',
 'Razor + unique peptides 05h_3',
 'Razor + unique peptides 05h_4',
 'Razor + unique peptides 06h_1',
 'Razor + unique peptides 06h_2',
 'Razor + unique peptides 06h_3',
 'Razor + unique peptides 06h_4',
 'Razor + unique peptides 08h_1',
 'Razor + unique peptides 08h_2',
 'Razor + unique peptides 08h_3',
 'Razor + unique peptides 08h_4',
 'Razor + unique peptides 10h_1',
 'Razor + unique peptides 10h_2',
 'Razor + unique peptides 10h_3',
 'Razor + unique peptides 10h_4',
 'Razor + unique peptides 12h_1',
 'Razor + unique peptides 12h_2',
 'Razor + unique peptides 12h_3',
 'Razor + unique peptides 12h_4',
 'Razor + unique peptides 14h_1',
 'Razor + unique peptides 14h_2',
 'Razor + unique peptides 14h_3',
 'Razor + unique peptides 14h_4',
 'Razor + unique peptides 16h_1',
 'Razor + unique peptides 16h_2',
 'Razor + unique peptides 16h_3',
 'Razor + unique peptides 16h_4',
 'Razor + unique peptides 18h_1',
 'Razor + unique peptides 18h_2',
 'Razor + unique peptides 18h_3',
 'Razor + unique peptides 18h_4',
 'Razor + unique peptides 20h_1',
 'Razor + unique peptides 20h_2',
 'Razor + unique peptides 20h_3',
 'Razor + unique peptides 20h_4',
 'Unique peptides 00h_1',
 'Unique peptides 00h_2',
 'Unique peptides 00h_3',
 'Unique peptides 00h_4',
 'Unique peptides 01h_1',
 'Unique peptides 01h_2',
 'Unique peptides 01h_3',
 'Unique peptides 01h_4',
 'Unique peptides 02h_1',
 'Unique peptides 02h_2',
 'Unique peptides 02h_3',
 'Unique peptides 02h_4',
 'Unique peptides 03h_1',
 'Unique peptides 03h_2',
 'Unique peptides 03h_3',
 'Unique peptides 03h_4',
 'Unique peptides 04h_1',
 'Unique peptides 04h_2',
 'Unique peptides 04h_3',
 'Unique peptides 04h_4',
 'Unique peptides 05h_1',
 'Unique peptides 05h_2',
 'Unique peptides 05h_3',
 'Unique peptides 05h_4',
 'Unique peptides 06h_1',
 'Unique peptides 06h_2',
 'Unique peptides 06h_3',
 'Unique peptides 06h_4',
 'Unique peptides 08h_1',
 'Unique peptides 08h_2',
 'Unique peptides 08h_3',
 'Unique peptides 08h_4',
 'Unique peptides 10h_1',
 'Unique peptides 10h_2',
 'Unique peptides 10h_3',
 'Unique peptides 10h_4',
 'Unique peptides 12h_1',
 'Unique peptides 12h_2',
 'Unique peptides 12h_3',
 'Unique peptides 12h_4',
 'Unique peptides 14h_1',
 'Unique peptides 14h_2',
 'Unique peptides 14h_3',
 'Unique peptides 14h_4',
 'Unique peptides 16h_1',
 'Unique peptides 16h_2',
 'Unique peptides 16h_3',
 'Unique peptides 16h_4',
 'Unique peptides 18h_1',
 'Unique peptides 18h_2',
 'Unique peptides 18h_3',
 'Unique peptides 18h_4',
 'Unique peptides 20h_1',
 'Unique peptides 20h_2',
 'Unique peptides 20h_3',
 'Unique peptides 20h_4',
 'Sequence coverage [%]',
 'Unique + razor sequence coverage [%]',
 'Unique sequence coverage [%]',
 'Mol. weight [kDa]',
 'Sequence length',
 'Sequence lengths',
 'Fraction average',
 'Fraction 1',
 'Fraction 2',
 'Fraction 3',
 'Fraction 4',
 'Fraction 5',
 'Fraction 6',
 'Fraction 7',
 'Fraction 8',
 'Fraction 9',
 'Fraction 10',
 'Fraction 11',
 'Fraction 12',
 'Fraction 13',
 'Fraction 14',
 'Q-value',
 'Score',
 'Identification type 00h_1',
 'Identification type 00h_2',
 'Identification type 00h_3',
 'Identification type 00h_4',
 'Identification type 01h_1',
 'Identification type 01h_2',
 'Identification type 01h_3',
 'Identification type 01h_4',
 'Identification type 02h_1',
 'Identification type 02h_2',
 'Identification type 02h_3',
 'Identification type 02h_4',
 'Identification type 03h_1',
 'Identification type 03h_2',
 'Identification type 03h_3',
 'Identification type 03h_4',
 'Identification type 04h_1',
 'Identification type 04h_2',
 'Identification type 04h_3',
 'Identification type 04h_4',
 'Identification type 05h_1',
 'Identification type 05h_2',
 'Identification type 05h_3',
 'Identification type 05h_4',
 'Identification type 06h_1',
 'Identification type 06h_2',
 'Identification type 06h_3',
 'Identification type 06h_4',
 'Identification type 08h_1',
 'Identification type 08h_2',
 'Identification type 08h_3',
 'Identification type 08h_4',
 'Identification type 10h_1',
 'Identification type 10h_2',
 'Identification type 10h_3',
 'Identification type 10h_4',
 'Identification type 12h_1',
 'Identification type 12h_2',
 'Identification type 12h_3',
 'Identification type 12h_4',
 'Identification type 14h_1',
 'Identification type 14h_2',
 'Identification type 14h_3',
 'Identification type 14h_4',
 'Identification type 16h_1',
 'Identification type 16h_2',
 'Identification type 16h_3',
 'Identification type 16h_4',
 'Identification type 18h_1',
 'Identification type 18h_2',
 'Identification type 18h_3',
 'Identification type 18h_4',
 'Identification type 20h_1',
 'Identification type 20h_2',
 'Identification type 20h_3',
 'Identification type 20h_4',
 'Sequence coverage 00h_1 [%]',
 'Sequence coverage 00h_2 [%]',
 'Sequence coverage 00h_3 [%]',
 'Sequence coverage 00h_4 [%]',
 'Sequence coverage 01h_1 [%]',
 'Sequence coverage 01h_2 [%]',
 'Sequence coverage 01h_3 [%]',
 'Sequence coverage 01h_4 [%]',
 'Sequence coverage 02h_1 [%]',
 'Sequence coverage 02h_2 [%]',
 'Sequence coverage 02h_3 [%]',
 'Sequence coverage 02h_4 [%]',
 'Sequence coverage 03h_1 [%]',
 'Sequence coverage 03h_2 [%]',
 'Sequence coverage 03h_3 [%]',
 'Sequence coverage 03h_4 [%]',
 'Sequence coverage 04h_1 [%]',
 'Sequence coverage 04h_2 [%]',
 'Sequence coverage 04h_3 [%]',
 'Sequence coverage 04h_4 [%]',
 'Sequence coverage 05h_1 [%]',
 'Sequence coverage 05h_2 [%]',
 'Sequence coverage 05h_3 [%]',
 'Sequence coverage 05h_4 [%]',
 'Sequence coverage 06h_1 [%]',
 'Sequence coverage 06h_2 [%]',
 'Sequence coverage 06h_3 [%]',
 'Sequence coverage 06h_4 [%]',
 'Sequence coverage 08h_1 [%]',
 'Sequence coverage 08h_2 [%]',
 'Sequence coverage 08h_3 [%]',
 'Sequence coverage 08h_4 [%]',
 'Sequence coverage 10h_1 [%]',
 'Sequence coverage 10h_2 [%]',
 'Sequence coverage 10h_3 [%]',
 'Sequence coverage 10h_4 [%]',
 'Sequence coverage 12h_1 [%]',
 'Sequence coverage 12h_2 [%]',
 'Sequence coverage 12h_3 [%]',
 'Sequence coverage 12h_4 [%]',
 'Sequence coverage 14h_1 [%]',
 'Sequence coverage 14h_2 [%]',
 'Sequence coverage 14h_3 [%]',
 'Sequence coverage 14h_4 [%]',
 'Sequence coverage 16h_1 [%]',
 'Sequence coverage 16h_2 [%]',
 'Sequence coverage 16h_3 [%]',
 'Sequence coverage 16h_4 [%]',
 'Sequence coverage 18h_1 [%]',
 'Sequence coverage 18h_2 [%]',
 'Sequence coverage 18h_3 [%]',
 'Sequence coverage 18h_4 [%]',
 'Sequence coverage 20h_1 [%]',
 'Sequence coverage 20h_2 [%]',
 'Sequence coverage 20h_3 [%]',
 'Sequence coverage 20h_4 [%]',
 'Intensity',
 'Intensity 00h_1',
 'Intensity 00h_2',
 'Intensity 00h_3',
 'Intensity 00h_4',
 'Intensity 01h_1',
 'Intensity 01h_2',
 'Intensity 01h_3',
 'Intensity 01h_4',
 'Intensity 02h_1',
 'Intensity 02h_2',
 'Intensity 02h_3',
 'Intensity 02h_4',
 'Intensity 03h_1',
 'Intensity 03h_2',
 'Intensity 03h_3',
 'Intensity 03h_4',
 'Intensity 04h_1',
 'Intensity 04h_2',
 'Intensity 04h_3',
 'Intensity 04h_4',
 'Intensity 05h_1',
 'Intensity 05h_2',
 'Intensity 05h_3',
 'Intensity 05h_4',
 'Intensity 06h_1',
 'Intensity 06h_2',
 'Intensity 06h_3',
 'Intensity 06h_4',
 'Intensity 08h_1',
 'Intensity 08h_2',
 'Intensity 08h_3',
 'Intensity 08h_4',
 'Intensity 10h_1',
 'Intensity 10h_2',
 'Intensity 10h_3',
 'Intensity 10h_4',
 'Intensity 12h_1',
 'Intensity 12h_2',
 'Intensity 12h_3',
 'Intensity 12h_4',
 'Intensity 14h_1',
 'Intensity 14h_2',
 'Intensity 14h_3',
 'Intensity 14h_4',
 'Intensity 16h_1',
 'Intensity 16h_2',
 'Intensity 16h_3',
 'Intensity 16h_4',
 'Intensity 18h_1',
 'Intensity 18h_2',
 'Intensity 18h_3',
 'Intensity 18h_4',
 'Intensity 20h_1',
 'Intensity 20h_2',
 'Intensity 20h_3',
 'Intensity 20h_4',
 'LFQ intensity 00h_1',
 'LFQ intensity 00h_2',
 'LFQ intensity 00h_3',
 'LFQ intensity 00h_4',
 'LFQ intensity 01h_1',
 'LFQ intensity 01h_2',
 'LFQ intensity 01h_3',
 'LFQ intensity 01h_4',
 'LFQ intensity 02h_1',
 'LFQ intensity 02h_2',
 'LFQ intensity 02h_3',
 'LFQ intensity 02h_4',
 'LFQ intensity 03h_1',
 'LFQ intensity 03h_2',
 'LFQ intensity 03h_3',
 'LFQ intensity 03h_4',
 'LFQ intensity 04h_1',
 'LFQ intensity 04h_2',
 'LFQ intensity 04h_3',
 'LFQ intensity 04h_4',
 'LFQ intensity 05h_1',
 'LFQ intensity 05h_2',
 'LFQ intensity 05h_3',
 'LFQ intensity 05h_4',
 'LFQ intensity 06h_1',
 'LFQ intensity 06h_2',
 'LFQ intensity 06h_3',
 'LFQ intensity 06h_4',
 'LFQ intensity 08h_1',
 'LFQ intensity 08h_2',
 'LFQ intensity 08h_3',
 'LFQ intensity 08h_4',
 'LFQ intensity 10h_1',
 'LFQ intensity 10h_2',
 'LFQ intensity 10h_3',
 'LFQ intensity 10h_4',
 'LFQ intensity 12h_1',
 'LFQ intensity 12h_2',
 'LFQ intensity 12h_3',
 'LFQ intensity 12h_4',
 'LFQ intensity 14h_1',
 'LFQ intensity 14h_2',
 'LFQ intensity 14h_3',
 'LFQ intensity 14h_4',
 'LFQ intensity 16h_1',
 'LFQ intensity 16h_2',
 'LFQ intensity 16h_3',
 'LFQ intensity 16h_4',
 'LFQ intensity 18h_1',
 'LFQ intensity 18h_2',
 'LFQ intensity 18h_3',
 'LFQ intensity 18h_4',
 'LFQ intensity 20h_1',
 'LFQ intensity 20h_2',
 'LFQ intensity 20h_3',
 'LFQ intensity 20h_4',
 'MS/MS Count 00h_1',
 'MS/MS Count 00h_2',
 'MS/MS Count 00h_3',
 'MS/MS Count 00h_4',
 'MS/MS Count 01h_1',
 'MS/MS Count 01h_2',
 'MS/MS Count 01h_3',
 'MS/MS Count 01h_4',
 'MS/MS Count 02h_1',
 'MS/MS Count 02h_2',
 'MS/MS Count 02h_3',
 'MS/MS Count 02h_4',
 'MS/MS Count 03h_1',
 'MS/MS Count 03h_2',
 'MS/MS Count 03h_3',
 'MS/MS Count 03h_4',
 'MS/MS Count 04h_1',
 'MS/MS Count 04h_2',
 'MS/MS Count 04h_3',
 'MS/MS Count 04h_4',
 'MS/MS Count 05h_1',
 'MS/MS Count 05h_2',
 'MS/MS Count 05h_3',
 'MS/MS Count 05h_4',
 'MS/MS Count 06h_1',
 'MS/MS Count 06h_2',
 'MS/MS Count 06h_3',
 'MS/MS Count 06h_4',
 'MS/MS Count 08h_1',
 'MS/MS Count 08h_2',
 'MS/MS Count 08h_3',
 'MS/MS Count 08h_4',
 'MS/MS Count 10h_1',
 'MS/MS Count 10h_2',
 'MS/MS Count 10h_3',
 'MS/MS Count 10h_4',
 'MS/MS Count 12h_1',
 'MS/MS Count 12h_2',
 'MS/MS Count 12h_3',
 'MS/MS Count 12h_4',
 'MS/MS Count 14h_1',
 'MS/MS Count 14h_2',
 'MS/MS Count 14h_3',
 'MS/MS Count 14h_4',
 'MS/MS Count 16h_1',
 'MS/MS Count 16h_2',
 'MS/MS Count 16h_3',
 'MS/MS Count 16h_4',
 'MS/MS Count 18h_1',
 'MS/MS Count 18h_2',
 'MS/MS Count 18h_3',
 'MS/MS Count 18h_4',
 'MS/MS Count 20h_1',
 'MS/MS Count 20h_2',
 'MS/MS Count 20h_3',
 'MS/MS Count 20h_4',
 'MS/MS Count',
 'Only identified by site',
 'Reverse',
 'Potential contaminant',
 'id',
 'Peptide IDs',
 'Peptide is razor',
 'Mod. peptide IDs',
 'Evidence IDs',
 'MS/MS IDs',
 'Best MS/MS',
 'Oxidation (M) site IDs',
 'Oxidation (M) site positions']

In [21]:
lfq_cols = []
for col in data_prot.columns:
    if "LFQ" in col:
        lfq_cols.append(col)

In [22]:
data_prot[lfq_cols]

,LFQ intensity 00h_1,LFQ intensity 00h_2,LFQ intensity 00h_3,LFQ intensity 00h_4,LFQ intensity 01h_1,LFQ intensity 01h_2,LFQ intensity 01h_3,LFQ intensity 01h_4,LFQ intensity 02h_1,LFQ intensity 02h_2,...,LFQ intensity 16h_3,LFQ intensity 16h_4,LFQ intensity 18h_1,LFQ intensity 18h_2,LFQ intensity 18h_3,LFQ intensity 18h_4,LFQ intensity 20h_1,LFQ intensity 20h_2,LFQ intensity 20h_3,LFQ intensity 20h_4
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,27247000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,65326000,0,0,0,0,0,0,0
3,14867000000,19851000000,17537000000,11980000000,15339000000,23228000000,14363000000,21518000000,18273000000,14665000000,...,8152900000,8136600000,27643000000,22550000000,15421000000,10228000000,19269000000,11009000000,11947000000,12650000000
4,0,0,0,0,0,0,0,94484000,0,0,...,0,0,0,0,173360000,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7382,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,548070000
7383,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7384,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7385,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7386,0,0,0,0,0,0,0,0,0,0,...,0,0,72745000,0,0,0,0,0,522590000,107850000

In [65]:
aux = proteins["Leading Proteins"].str.split(";",expand=True)
len(aux[aux[1].isna()][0].unique())

7368

In [8]:
data_prot[['Only identified by site','Reverse','Potential contaminant']]

     Only identified by site Reverse Potential contaminant
0                          +     NaN                     +
1                          +     NaN                     +
2                        NaN     NaN                     +
3                        NaN     NaN                     +
4                        NaN     NaN                     +
...                      ...     ...                   ...
7382                       +     NaN                   NaN
7383                     NaN     NaN                   NaN
7384                     NaN     NaN                   NaN
7385                     NaN     NaN                   NaN
7386                     NaN     NaN                   NaN

[7387 rows x 3 columns]

In [13]:
data_prot_filtered = data_prot[(data_prot["Potential contaminant"].isna())&(data_prot["Reverse"].isna())&(data_prot["Only identified by site"].isna())]
data_prot_filtered

,Protein IDs,Majority protein IDs,Peptide counts (all),Peptide counts (razor+unique),Peptide counts (unique),Fasta headers,Number of proteins,Peptides,Razor + unique peptides,Unique peptides,...,Potential contaminant,id,Peptide IDs,Peptide is razor,Mod. peptide IDs,Evidence IDs,MS/MS IDs,Best MS/MS,Oxidation (M) site IDs,Oxidation (M) site positions
32,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,38;38;38;37;37,38;38;38;37;37,38;38;38;37;37,>FBpp0293227 pep:known chromosome:BDGP6:2L:836...,5,38,38,38,...,NaN,32,8588;8589;10959;11620;11774;13083;14193;16539;...,True;True;True;True;True;True;True;True;True;T...,9221;9222;11710;12405;12563;13928;15087;17564;...,295478;295479;295480;295481;295482;295483;2954...,253921;253922;253923;253924;253925;253926;2539...,253998;254035;318305;336550;340124;377394;4068...,32;33;34;35;36;37,182;429;450;468;487;491
33,FBtr0070007,FBtr0070007,25,25,25,>FBpp0070006 pep:known chromosome:BDGP6:X:2016...,1,25,25,25,...,NaN,33,1061;3911;8594;11543;11544;17193;19894;22633;2...,True;True;True;True;True;True;True;True;True;T...,1127;4170;9228;12325;12326;18260;21102;24040;2...,39824;39825;39826;39827;39828;39829;39830;3983...,36621;36622;36623;36624;36625;36626;36627;3662...,36625;115033;254214;334784;334813;484840;55319...,38,188
34,FBtr0070008,FBtr0070008,11,11,11,>FBpp0070007 pep:known chromosome:BDGP6:X:2017...,1,11,11,11,...,NaN,34,12092;16957;21453;26103;26715;65324;65325;9131...,True;True;True;True;True;True;True;True;True;T...,12899;18012;22811;27697;28345;69522;69523;9809...,407830;562079;702614;702615;702616;702617;7026...,350697;478270;594644;594645;594646;594647;5946...,350697;478270;594646;718659;738330;1874770;187...,NaN,NaN
35,FBtr0070025,FBtr0070025,19,19,1,>FBpp0070024 pep:known chromosome:BDGP6:X:2017...,1,19,19,1,...,NaN,35,5389;5743;9063;10903;12253;21845;31295;45758;5...,True;True;True;True;True;True;True;True;True;T...,5747;6173;9725;11650;13067;23220;33251;48750;6...,186189;186190;186191;186192;186193;186194;1861...,159044;159045;159046;159047;159048;159049;1590...,159074;172863;269049;317212;356064;603851;8807...,39;40,1;141
36,FBtr0070026,FBtr0070026,28,28,28,>FBpp0070025 pep:known chromosome:BDGP6:X:2016...,1,28,28,28,...,NaN,36,2502;5210;14650;21049;24696;34088;34089;35878;...,True;True;True;True;True;True;True;True;True;T...,2664;5558;15587;22335;26213;36270;36271;38169;...,84300;84301;84302;84303;84304;84305;84306;8430...,73742;73743;73744;73745;73746;73747;73748;7374...,73810;153556;419772;582379;676395;969977;97003...,41;42;43,244;265;292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7381,YPR082C,YPR082C,1,1,1,>YPR082C pep:known chromosome:R64-1-1:XVI:7042...,1,1,1,1,...,NaN,7381,33724,True,35834,1125382;1125383;1125384;1125385;1125386;112538...,959589;959590;959591;959592;959593;959594;9595...,959618,NaN,NaN
7383,YPR149W,YPR149W,3,3,3,>YPR149W pep:known chromosome:R64-1-1:XVI:8299...,1,3,3,3,...,NaN,7383,3177;88865;103437,True;True;True,3393;95513;111034,109099;2959069;3427333;3427334,94286;2480988;2874985,94286;2480988;2874985,NaN,NaN
7384,YPR160W,YPR160W,15,13,13,>YPR160W pep:known chromosome:R64-1-1:XVI:8613...,1,15,13,13,...,NaN,7384,1763;4417;14484;15781;26253;29391;70366;74722;...,True;True;True;True;True;True;True;True;True;T...,1872;4708;15411;16764;27852;31232;74874;80582;...,60995;152805;485692;485693;485694;485695;48569...,53995;130215;415309;445585;723388;723389;72339...,53995;130215;415309;445585;723390;816979;20149...,NaN,NaN
7385,YPR183W,YPR183W,9,9,9,>YPR183W pep:known chromosome:R64-1-1:XVI:9007...,1,9,9,9,...,NaN,7385,40852;58040;58189;64171;80390;92965;107575;110...,True;True;True;True;True;True;True;True;True,43471;61738;61901;68298;86616;99856;115485;118...,1372366;1372367;1372368;1372369;1372370;137237...,1164843;1164844;1164845;1164846;1164847;166664...,1164844;1666643;1670496;1842181;2291233;258760...,NaN,NaN
7386,YPR191W,YPR191W,22,22,22,>YPR191W pep:known chromosome:R64-1-1:XVI:9193...,1,22,22,22,...,NaN,7386,7900;12392;14067;14767;14768;22463;26337;27628...,True;True;True;True;True;True;True;True;True;T...,8491;13215;14953;15709;15710;23862;27941;29374...,271786;271787;271788;271789;271790;271791;2717...,233136;233137;233138;233139;233140;233141;3600...,233138;360083;402909;422830;422832;616955;7264...,NaN,NaN

In [17]:
aux = data_prot_filtered["Majority protein IDs"].str.split(";", expand=True)
aux["Protein IDs"] = data_prot_filtered["Protein IDs"]
aux

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,Protein IDs
32,FBtr0100535,FBtr0100533,FBtr0005088,FBtr0339789,FBtr0306102,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...
33,FBtr0070007,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070007
34,FBtr0070008,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070008
35,FBtr0070025,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070025
36,FBtr0070026,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7381,YPR082C,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR082C
7383,YPR149W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR149W
7384,YPR160W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR160W
7385,YPR183W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR183W
7386,YPR191W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR191W

In [45]:
one = aux[aux[1].isna()]
one

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,Protein IDs
33,FBtr0070007,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070007
34,FBtr0070008,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070008
35,FBtr0070025,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070025
36,FBtr0070026,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070026
39,FBtr0070038,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0070038;FBtr0339894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7381,YPR082C,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR082C
7383,YPR149W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR149W
7384,YPR160W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR160W
7385,YPR183W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR183W
7386,YPR191W,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPR191W

In [46]:
more = aux[~aux[1].isna()]
more

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,Protein IDs
32,FBtr0100535,FBtr0100533,FBtr0005088,FBtr0339789,FBtr0306102,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...
37,FBtr0333547,FBtr0333546,FBtr0070027,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0333547;FBtr0333546;FBtr0070027
38,FBtr0333549,FBtr0303258,FBtr0070028,FBtr0333548,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0333549;FBtr0303258;FBtr0070028;FBtr0333548
40,FBtr0331408,FBtr0070041,FBtr0070040,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0331408;FBtr0070041;FBtr0070040
41,FBtr0345139,FBtr0345138,FBtr0344974,FBtr0111141,FBtr0070044,FBtr0070043,FBtr0070042,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0345139;FBtr0345138;FBtr0344974;FBtr011114...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7327,YOR167C,YLR264W,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YOR167C;YLR264W
7333,YOR204W,YPL119C,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YOR204W;YPL119C
7340,YOR293W,YMR230W,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YOR293W;YMR230W
7350,YPL036W,YGL008C,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPL036W;YGL008C
7355,YPL079W,YBR191W,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,YPL079W;YBR191W

In [25]:
aliases = pd.read_csv("data/7227.protein.aliases.v12.0.txt", sep="\t")
aliases.head()

  #string_protein_id             alias              source
0   7227.FBpp0070001             33009  Ensembl_EntrezGene
1   7227.FBpp0070001             33009         KEGG_GENEID
2   7227.FBpp0070001             33009   UniProt_DR_GeneID
3   7227.FBpp0070001  7227.FBpp0070001      Ensembl_STRING
4   7227.FBpp0070001        AAF45383.1  Ensembl_protein_id

In [102]:
keep_same_proteins = []
for i in range(len(more)):
    row = more.iloc[i]
    first_col = row[0]
    first_col_string = aliases[aliases["alias"]==first_col]["#string_protein_id"].drop_duplicates()
    
    print(i)
    if len(first_col_string)>0:
        j=1
        write=True
        while row[j]!=None and j!=26:
            current = row[j]
            current_string = aliases[aliases["alias"]==current]["#string_protein_id"].drop_duplicates()
            if len(current_string)==0:
                write=False
                break
            if current_string.item() != first_col_string.item():
                write=False
                break
            j+=1
        if write:
            keep_same_proteins.append(row["Protein IDs"])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860

1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190
3191
3192
3193
3194
3195
3196
3197
3198
3199
3200
3201
3202
3203
3204
3205
3206
3207
3208
3209
3210
3211
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3225
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3250
3251
3252
3253
3254
3255
3256
3257
3258
3259
3260
3261
3262
3263
3264
3265
3266
3267
3268
3269
3270
3271
3272
3273
3274
3275
3276
3277
3278
3279
3280
3281
3282
3283
3284
3285
3286
3287
3288
3289
3290
3291
3292
3293
3294
3295
3296
3297
3298
3299
3300
3301
3302
3303
3304
3305
3306
3307
3308
3309
3310
3311
3312
3313
3314
3315
3316
3317
3318
3319
3320
3321
3322
3323
3324
3325
3326
3327
3328
3329
3330
3331
3332
3333
3334
3335
3336
3337
3338
3339
3340
3341
3342
3343
3344
3345
3346
3347
3348
3349
3350
3351
3352
3353
3354
3355
3356
3357
3358
3359
3360
3361
3362
3363
3364
3365
3366
3367
3368
3369
3370
3371
3372
3373
3374
3375
3376
3377
3378
3379
3380
3381
3382
3383
3384
3385
3386
3387
3388
3389
3390
3391
3392
3393
3394
3395
3396
3397
3398
3399
3400
3401
3402
3403
3404
3405
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
3437
3438
3439
3440
3441
3442
3443
3444
3445
3446
3447
3448
3449
3450
3451
3452
3453
3454
3455
3456
3457
3458
3459
3460
3461
3462
3463
3464
3465
3466
3467
3468
3469
3470
3471
3472
3473
3474
3475
3476
3477
3478
3479
3480
3481
3482
3483
3484
3485
3486
3487
3488
3489
3490
3491
3492
3493
3494
3495
3496
3497
3498
3499

3500
3501
3502
3503
3504
3505
3506
3507
3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966

In [103]:
len(keep_same_proteins)

3827

In [104]:
more[more["Protein IDs"].isin(keep_same_proteins)]

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,Protein IDs
32,FBtr0100535,FBtr0100533,FBtr0005088,FBtr0339789,FBtr0306102,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...
37,FBtr0333547,FBtr0333546,FBtr0070027,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0333547;FBtr0333546;FBtr0070027
38,FBtr0333549,FBtr0303258,FBtr0070028,FBtr0333548,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0333549;FBtr0303258;FBtr0070028;FBtr0333548
40,FBtr0331408,FBtr0070041,FBtr0070040,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0331408;FBtr0070041;FBtr0070040
41,FBtr0345139,FBtr0345138,FBtr0344974,FBtr0111141,FBtr0070044,FBtr0070043,FBtr0070042,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0345139;FBtr0345138;FBtr0344974;FBtr011114...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6644,FBtr0345109,FBtr0345111,FBtr0345110,FBtr0345100,FBtr0345093,FBtr0345102,FBtr0345099,FBtr0345088,FBtr0345087,FBtr0345092,...,None,None,None,None,None,None,None,None,None,FBtr0345109;FBtr0345111;FBtr0345110;FBtr034510...
6645,FBtr0345112,FBtr0345104,FBtr0345105,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0345112;FBtr0345104;FBtr0345105;FBtr034510...
6646,FBtr0345460,FBtr0346729,FBtr0346728,FBtr0345457,FBtr0345459,FBtr0345458,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0345460;FBtr0346729;FBtr0346728;FBtr034545...
6650,FBtr0346819,FBtr0346817,FBtr0346818,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0346819;FBtr0346817;FBtr0346818
6651,FBtr0346961,FBtr0088263,FBtr0306247,FBtr0100460,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,FBtr0346961;FBtr0088263;FBtr0306247;FBtr0100460

In [105]:
data_prot_filtered2 = data_prot_filtered[(data_prot_filtered['Protein IDs'].isin(keep_same_proteins))|(data_prot_filtered["Protein IDs"].isin(one["Protein IDs"]))]
data_prot_filtered2

,Protein IDs,Majority protein IDs,Peptide counts (all),Peptide counts (razor+unique),Peptide counts (unique),Fasta headers,Number of proteins,Peptides,Razor + unique peptides,Unique peptides,...,Potential contaminant,id,Peptide IDs,Peptide is razor,Mod. peptide IDs,Evidence IDs,MS/MS IDs,Best MS/MS,Oxidation (M) site IDs,Oxidation (M) site positions
32,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,38;38;38;37;37,38;38;38;37;37,38;38;38;37;37,>FBpp0293227 pep:known chromosome:BDGP6:2L:836...,5,38,38,38,...,NaN,32,8588;8589;10959;11620;11774;13083;14193;16539;...,True;True;True;True;True;True;True;True;True;T...,9221;9222;11710;12405;12563;13928;15087;17564;...,295478;295479;295480;295481;295482;295483;2954...,253921;253922;253923;253924;253925;253926;2539...,253998;254035;318305;336550;340124;377394;4068...,32;33;34;35;36;37,182;429;450;468;487;491
33,FBtr0070007,FBtr0070007,25,25,25,>FBpp0070006 pep:known chromosome:BDGP6:X:2016...,1,25,25,25,...,NaN,33,1061;3911;8594;11543;11544;17193;19894;22633;2...,True;True;True;True;True;True;True;True;True;T...,1127;4170;9228;12325;12326;18260;21102;24040;2...,39824;39825;39826;39827;39828;39829;39830;3983...,36621;36622;36623;36624;36625;36626;36627;3662...,36625;115033;254214;334784;334813;484840;55319...,38,188
34,FBtr0070008,FBtr0070008,11,11,11,>FBpp0070007 pep:known chromosome:BDGP6:X:2017...,1,11,11,11,...,NaN,34,12092;16957;21453;26103;26715;65324;65325;9131...,True;True;True;True;True;True;True;True;True;T...,12899;18012;22811;27697;28345;69522;69523;9809...,407830;562079;702614;702615;702616;702617;7026...,350697;478270;594644;594645;594646;594647;5946...,350697;478270;594646;718659;738330;1874770;187...,NaN,NaN
35,FBtr0070025,FBtr0070025,19,19,1,>FBpp0070024 pep:known chromosome:BDGP6:X:2017...,1,19,19,1,...,NaN,35,5389;5743;9063;10903;12253;21845;31295;45758;5...,True;True;True;True;True;True;True;True;True;T...,5747;6173;9725;11650;13067;23220;33251;48750;6...,186189;186190;186191;186192;186193;186194;1861...,159044;159045;159046;159047;159048;159049;1590...,159074;172863;269049;317212;356064;603851;8807...,39;40,1;141
36,FBtr0070026,FBtr0070026,28,28,28,>FBpp0070025 pep:known chromosome:BDGP6:X:2016...,1,28,28,28,...,NaN,36,2502;5210;14650;21049;24696;34088;34089;35878;...,True;True;True;True;True;True;True;True;True;T...,2664;5558;15587;22335;26213;36270;36271;38169;...,84300;84301;84302;84303;84304;84305;84306;8430...,73742;73743;73744;73745;73746;73747;73748;7374...,73810;153556;419772;582379;676395;969977;97003...,41;42;43,244;265;292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7381,YPR082C,YPR082C,1,1,1,>YPR082C pep:known chromosome:R64-1-1:XVI:7042...,1,1,1,1,...,NaN,7381,33724,True,35834,1125382;1125383;1125384;1125385;1125386;112538...,959589;959590;959591;959592;959593;959594;9595...,959618,NaN,NaN
7383,YPR149W,YPR149W,3,3,3,>YPR149W pep:known chromosome:R64-1-1:XVI:8299...,1,3,3,3,...,NaN,7383,3177;88865;103437,True;True;True,3393;95513;111034,109099;2959069;3427333;3427334,94286;2480988;2874985,94286;2480988;2874985,NaN,NaN
7384,YPR160W,YPR160W,15,13,13,>YPR160W pep:known chromosome:R64-1-1:XVI:8613...,1,15,13,13,...,NaN,7384,1763;4417;14484;15781;26253;29391;70366;74722;...,True;True;True;True;True;True;True;True;True;T...,1872;4708;15411;16764;27852;31232;74874;80582;...,60995;152805;485692;485693;485694;485695;48569...,53995;130215;415309;445585;723388;723389;72339...,53995;130215;415309;445585;723390;816979;20149...,NaN,NaN
7385,YPR183W,YPR183W,9,9,9,>YPR183W pep:known chromosome:R64-1-1:XVI:9007...,1,9,9,9,...,NaN,7385,40852;58040;58189;64171;80390;92965;107575;110...,True;True;True;True;True;True;True;True;True,43471;61738;61901;68298;86616;99856;115485;118...,1372366;1372367;1372368;1372369;1372370;137237...,1164843;1164844;1164845;1164846;1164847;166664...,1164844;1666643;1670496;1842181;2291233;258760...,NaN,NaN
7386,YPR191W,YPR191W,22,22,22,>YPR191W pep:known chromosome:R64-1-1:XVI:9193...,1,22,22,22,...,NaN,7386,7900;12392;14067;14767;14768;22463;26337;27628...,True;True;True;True;True;True;True;True;True;T...,8491;13215;14953;15709;15710;23862;27941;29374...,271786;271787;271788;271789;271790;271791;2717...,233136;233137;233138;233139;233140;233141;3600...,233138;360083;402909;422830;422832;616955;7264...,NaN,NaN

In [108]:
final_names = data_prot_filtered2["Majority protein IDs"].str.split(";",expand=True)[[0]]
final_names["Protein IDs"] = data_prot_filtered2["Protein IDs"]
final_names["Majority protein IDs"] = data_prot_filtered2["Majority protein IDs"]
final_names

,0,Protein IDs,Majority protein IDs
32,FBtr0100535,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...
33,FBtr0070007,FBtr0070007,FBtr0070007
34,FBtr0070008,FBtr0070008,FBtr0070008
35,FBtr0070025,FBtr0070025,FBtr0070025
36,FBtr0070026,FBtr0070026,FBtr0070026
...,...,...,...
7381,YPR082C,YPR082C,YPR082C
7383,YPR149W,YPR149W,YPR149W
7384,YPR160W,YPR160W,YPR160W
7385,YPR183W,YPR183W,YPR183W
7386,YPR191W,YPR191W,YPR191W

In [109]:
len(final_names[0].unique())

6915

In [112]:
final_names.to_csv("data/drosophila_m_protein_names.csv", index=False)

In [113]:
string_info = pd.read_csv("data/7227.protein.info.v12.0.txt", sep="\t")
string_info.head()

,#string_protein_id,preferred_name,protein_size,annotation
0,7227.FBpp0070001,CG9570,210,AT16669p.
1,7227.FBpp0070002,Or19b,387,Putative odorant receptor 19b; Odorant recepto...
2,7227.FBpp0070005,CG9572,441,LP13770p.
3,7227.FBpp0070006,CG9577,312,"RE22677p; delta3,5-delta2,4-dienoyl-CoA isomer..."
4,7227.FBpp0070007,CG9578,272,HL08141p; It is involved in the biological pro...

In [120]:
matched_proteins = aliases[aliases["alias"].isin(final_names[0])][["#string_protein_id","alias"]].drop_duplicates()
matched_proteins

       #string_protein_id        alias
170      7227.FBpp0070006  FBtr0070007
210      7227.FBpp0070007  FBtr0070008
253      7227.FBpp0070025  FBtr0070026
467      7227.FBpp0070037  FBtr0070038
524      7227.FBpp0070044  FBtr0070045
...                   ...          ...
852335   7227.FBpp0423183  FBtr0344622
852460   7227.FBpp0423185  FBtr0332196
852702   7227.FBpp0423189  FBtr0075327
853212   7227.FBpp0423205  FBtr0072805
853300   7227.FBpp0423206  FBtr0310001

[6390 rows x 2 columns]

In [122]:
len(matched_proteins['alias'].unique()), len(matched_proteins['#string_protein_id'].unique())

(6390, 6221)

In [123]:
aux_match = matched_proteins.groupby("#string_protein_id").count()
aux_match[aux_match["alias"]>1]

                    alias
#string_protein_id
7227.FBpp0070331        2
7227.FBpp0071081        2
7227.FBpp0071097        2
7227.FBpp0071116        2
7227.FBpp0071148        2
...                   ...
7227.FBpp0309831        4
7227.FBpp0310068        2
7227.FBpp0311337        2
7227.FBpp0311505        2
7227.FBpp0311822        2

[132 rows x 1 columns]

In [128]:
to_check = matched_proteins[matched_proteins["#string_protein_id"].isin(aux_match[aux_match["alias"]>1].index)]
to_check

       #string_protein_id        alias
6623     7227.FBpp0070331  FBtr0070344
6637     7227.FBpp0070331  FBtr0333802
22889    7227.FBpp0071081  FBtr0071129
22891    7227.FBpp0071081  FBtr0071130
23254    7227.FBpp0071097  FBtr0071145
...                   ...          ...
795755   7227.FBpp0311337  FBtr0345112
800012   7227.FBpp0311505  FBtr0089322
800014   7227.FBpp0311505  FBtr0345350
815349   7227.FBpp0311822  FBtr0330262
815367   7227.FBpp0311822  FBtr0345898

[301 rows x 2 columns]

In [130]:
to_check_merged = aliases.merge(to_check)
to_check_merged

    #string_protein_id        alias                         source
0     7227.FBpp0070331  FBtr0070344  Ensembl_flybase_transcript_id
1     7227.FBpp0070331  FBtr0070344             Ensembl_transcript
2     7227.FBpp0070331  FBtr0333802  Ensembl_flybase_transcript_id
3     7227.FBpp0070331  FBtr0333802             Ensembl_transcript
4     7227.FBpp0071081  FBtr0071129  Ensembl_flybase_transcript_id
..                 ...          ...                            ...
598   7227.FBpp0311505  FBtr0345350             Ensembl_transcript
599   7227.FBpp0311822  FBtr0330262  Ensembl_flybase_transcript_id
600   7227.FBpp0311822  FBtr0330262             Ensembl_transcript
601   7227.FBpp0311822  FBtr0345898  Ensembl_flybase_transcript_id
602   7227.FBpp0311822  FBtr0345898             Ensembl_transcript

[603 rows x 3 columns]

In [131]:
to_check_merged["source"].unique()

array(['Ensembl_flybase_transcript_id', 'Ensembl_transcript',
       'UniProt_GN_Synonyms'], dtype=object)

In [137]:
to_check_merged[to_check_merged["source"].isin(['Ensembl_flybase_transcript_id'])].drop_duplicates()

    #string_protein_id        alias                         source
0     7227.FBpp0070331  FBtr0070344  Ensembl_flybase_transcript_id
2     7227.FBpp0070331  FBtr0333802  Ensembl_flybase_transcript_id
4     7227.FBpp0071081  FBtr0071129  Ensembl_flybase_transcript_id
6     7227.FBpp0071081  FBtr0071130  Ensembl_flybase_transcript_id
8     7227.FBpp0071097  FBtr0071145  Ensembl_flybase_transcript_id
..                 ...          ...                            ...
593   7227.FBpp0311337  FBtr0345112  Ensembl_flybase_transcript_id
595   7227.FBpp0311505  FBtr0089322  Ensembl_flybase_transcript_id
597   7227.FBpp0311505  FBtr0345350  Ensembl_flybase_transcript_id
599   7227.FBpp0311822  FBtr0330262  Ensembl_flybase_transcript_id
601   7227.FBpp0311822  FBtr0345898  Ensembl_flybase_transcript_id

[301 rows x 3 columns]

Different transcripts mapping to the same protein --> one node in the network (the protein) --> max LFQ or intensity of the transcripts should be considered!

** Merge mapping with original protein data --> groupby string protein name --> max of LFQs **

In [142]:
matched_proteins = aliases[aliases["alias"].isin(final_names[0])]
matched_proteins = matched_proteins[matched_proteins["source"]=="Ensembl_flybase_transcript_id"][["#string_protein_id","alias"]]
matched_proteins

       #string_protein_id        alias
170      7227.FBpp0070006  FBtr0070007
210      7227.FBpp0070007  FBtr0070008
253      7227.FBpp0070025  FBtr0070026
467      7227.FBpp0070037  FBtr0070038
524      7227.FBpp0070044  FBtr0070045
...                   ...          ...
852335   7227.FBpp0423183  FBtr0344622
852460   7227.FBpp0423185  FBtr0332196
852702   7227.FBpp0423189  FBtr0075327
853212   7227.FBpp0423205  FBtr0072805
853300   7227.FBpp0423206  FBtr0310001

[6390 rows x 2 columns]

In [146]:
cols_to_keep = ['Protein IDs', 'Majority protein IDs', 'Peptide counts (all)',
       'Peptide counts (razor+unique)', 'Peptide counts (unique)', 'Number of proteins']
for col in data_prot_filtered2.columns:
    if "LFQ" in col:
        cols_to_keep.append(col)

In [148]:
data_prot_filtered3 = data_prot_filtered2[cols_to_keep]
data_prot_filtered3 = data_prot_filtered3.merge(final_names)
data_prot_filtered3

,Protein IDs,Majority protein IDs,Peptide counts (all),Peptide counts (razor+unique),Peptide counts (unique),Number of proteins,LFQ intensity 00h_1,LFQ intensity 00h_2,LFQ intensity 00h_3,LFQ intensity 00h_4,...,LFQ intensity 16h_4,LFQ intensity 18h_1,LFQ intensity 18h_2,LFQ intensity 18h_3,LFQ intensity 18h_4,LFQ intensity 20h_1,LFQ intensity 20h_2,LFQ intensity 20h_3,LFQ intensity 20h_4,0
0,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,38;38;38;37;37,38;38;38;37;37,38;38;38;37;37,5,8927500000,8046700000,7817900000,7614100000,...,12565000000,10021000000,10118000000,10723000000,8932200000,10595000000,8951300000,7163900000,8104800000,FBtr0100535
1,FBtr0070007,FBtr0070007,25,25,25,1,7139700000,7000300000,7351500000,6736800000,...,3308500000,3855400000,3004600000,4145500000,4520000000,2603000000,4208200000,4399300000,4756100000,FBtr0070007
2,FBtr0070008,FBtr0070008,11,11,11,1,75231000,0,0,0,...,0,89605000,69869000,61999000,84881000,84614000,0,96916000,73657000,FBtr0070008
3,FBtr0070025,FBtr0070025,19,19,1,1,0,0,0,0,...,97147000,114390000,127810000,146620000,0,0,91865000,0,0,FBtr0070025
4,FBtr0070026,FBtr0070026,28,28,28,1,3637800000,4060100000,4368200000,4302300000,...,2176600000,1586300000,1637800000,2081200000,2515700000,1801100000,2398700000,2336100000,2638700000,FBtr0070026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6910,YPR082C,YPR082C,1,1,1,1,0,0,0,0,...,0,233710000,327760000,314380000,112450000,233740000,250040000,135880000,0,YPR082C
6911,YPR149W,YPR149W,3,3,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,YPR149W
6912,YPR160W,YPR160W,15,13,13,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,YPR160W
6913,YPR183W,YPR183W,9,9,9,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,YPR183W
6914,YPR191W,YPR191W,22,22,22,1,0,0,0,0,...,0,72745000,0,0,0,0,0,522590000,107850000,YPR191W

In [149]:
data_prot_filtered4 = data_prot_filtered3.merge(matched_proteins, left_on=0, right_on="alias")
data_prot_filtered4

,Protein IDs,Majority protein IDs,Peptide counts (all),Peptide counts (razor+unique),Peptide counts (unique),Number of proteins,LFQ intensity 00h_1,LFQ intensity 00h_2,LFQ intensity 00h_3,LFQ intensity 00h_4,...,LFQ intensity 18h_2,LFQ intensity 18h_3,LFQ intensity 18h_4,LFQ intensity 20h_1,LFQ intensity 20h_2,LFQ intensity 20h_3,LFQ intensity 20h_4,0,#string_protein_id,alias
0,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,FBtr0100535;FBtr0100533;FBtr0005088;FBtr033978...,38;38;38;37;37,38;38;38;37;37,38;38;38;37;37,5,8927500000,8046700000,7817900000,7614100000,...,10118000000,10723000000,8932200000,10595000000,8951300000,7163900000,8104800000,FBtr0100535,7227.FBpp0308836,FBtr0100535
1,FBtr0070007,FBtr0070007,25,25,25,1,7139700000,7000300000,7351500000,6736800000,...,3004600000,4145500000,4520000000,2603000000,4208200000,4399300000,4756100000,FBtr0070007,7227.FBpp0070006,FBtr0070007
2,FBtr0070008,FBtr0070008,11,11,11,1,75231000,0,0,0,...,69869000,61999000,84881000,84614000,0,96916000,73657000,FBtr0070008,7227.FBpp0070007,FBtr0070008
3,FBtr0070025,FBtr0070025,19,19,1,1,0,0,0,0,...,127810000,146620000,0,0,91865000,0,0,FBtr0070025,7227.FBpp0291143,FBtr0070025
4,FBtr0070026,FBtr0070026,28,28,28,1,3637800000,4060100000,4368200000,4302300000,...,1637800000,2081200000,2515700000,1801100000,2398700000,2336100000,2638700000,FBtr0070026,7227.FBpp0070025,FBtr0070026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6385,FBtr0345460;FBtr0346729;FBtr0346728;FBtr034545...,FBtr0345460;FBtr0346729;FBtr0346728;FBtr034545...,9;7;7;7;7;7,9;7;7;7;7;7,9;7;7;7;7;7,6,0,0,0,0,...,0,0,0,0,0,0,0,FBtr0345460,7227.FBpp0311578,FBtr0345460
6386,FBtr0346609,FBtr0346609,2,2,2,1,0,0,11544000,13433000,...,0,0,0,13649000,0,0,0,FBtr0346609,7227.FBpp0312189,FBtr0346609
6387,FBtr0346714,FBtr0346714,33,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,FBtr0346714,7227.FBpp0289791,FBtr0346714
6388,FBtr0346819;FBtr0346817;FBtr0346818,FBtr0346819;FBtr0346817;FBtr0346818,11;11;11,11;11;11,11;11;11,3,0,0,0,0,...,0,0,0,0,0,0,0,FBtr0346819,7227.FBpp0312393,FBtr0346819
6389,FBtr0346961;FBtr0088263;FBtr0306247;FBtr0100460,FBtr0346961;FBtr0088263;FBtr0306247;FBtr0100460,30;29;29;28,30;29;29;28,1;1;1;1,4,0,0,0,0,...,0,0,0,0,0,0,0,FBtr0346961,7227.FBpp0312425,FBtr0346961

In [158]:
final = data_prot_filtered4[list(data_prot_filtered4.columns[6:-3])+["#string_protein_id"]].groupby("#string_protein_id").max().reset_index()
final

,#string_protein_id,LFQ intensity 00h_1,LFQ intensity 00h_2,LFQ intensity 00h_3,LFQ intensity 00h_4,LFQ intensity 01h_1,LFQ intensity 01h_2,LFQ intensity 01h_3,LFQ intensity 01h_4,LFQ intensity 02h_1,...,LFQ intensity 16h_3,LFQ intensity 16h_4,LFQ intensity 18h_1,LFQ intensity 18h_2,LFQ intensity 18h_3,LFQ intensity 18h_4,LFQ intensity 20h_1,LFQ intensity 20h_2,LFQ intensity 20h_3,LFQ intensity 20h_4
0,7227.FBpp0070006,7139700000,7000300000,7351500000,6736800000,6931000000,7486800000,6157100000,8548400000,6499200000,...,4688600000,3308500000,3855400000,3004600000,4145500000,4520000000,2603000000,4208200000,4399300000,4756100000
1,7227.FBpp0070007,75231000,0,0,0,0,0,0,0,0,...,135760000,0,89605000,69869000,61999000,84881000,84614000,0,96916000,73657000
2,7227.FBpp0070025,3637800000,4060100000,4368200000,4302300000,3532500000,4588400000,3801400000,4847400000,3936000000,...,2301900000,2176600000,1586300000,1637800000,2081200000,2515700000,1801100000,2398700000,2336100000,2638700000
3,7227.FBpp0070037,199850000,156800000,67311000,33066000,61112000,47458000,45311000,117150000,414390000,...,2359200000,2097500000,1768600000,1619000000,2556200000,2049800000,2362500000,1967200000,2016400000,2205700000
4,7227.FBpp0070044,328010000,286710000,273800000,263190000,150780000,149450000,364990000,302150000,376590000,...,1164800000,651090000,603400000,497560000,903200000,1219100000,1433800000,1065600000,1383800000,1164900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6216,7227.FBpp0423183,1227600000,1538500000,1636200000,1596900000,1060300000,1053800000,950860000,1144400000,1155700000,...,902470000,993540000,909080000,766040000,709320000,773310000,729360000,931090000,880320000,824380000
6217,7227.FBpp0423185,0,0,0,0,0,0,0,0,0,...,0,0,0,68024000,0,0,35089000,0,0,0
6218,7227.FBpp0423189,405410000,589330000,654830000,464990000,601980000,515040000,517940000,539750000,646820000,...,187070000,177550000,230970000,184780000,176680000,232020000,289530000,256150000,267550000,219420000
6219,7227.FBpp0423205,14816000000,10171000000,11812000000,13545000000,12379000000,14256000000,14059000000,14860000000,14990000000,...,20494000000,26223000000,20767000000,37229000000,18365000000,20365000000,22359000000,16057000000,14881000000,14927000000
6220,7227.FBpp0423206,0,0,0,0,0,0,0,0,0,...,0,0,9358100,0,0,0,0,0,0,0

In [159]:
final.to_csv("data/drosophila_m_lfq_mapped_to_string.csv", index=False)